### ISSUE TITLE
Reversed EnumFacing

### ISSUE THREAD

**Issue by pauljoda** [Vanhal/ProgressiveAutomation#103]
In your 1.8 update, you're passing the wrong direction to the tile receiving energy. With EnumFacing, you need to pass the opposite of the direction you're traveling into the receiver. It looks like you are trying to do that but "getFront(i)" does not return the opposite. It returns the value for that integer.
![capture](https://cloud.githubusercontent.com/assets/3199533/6789276/280496a4-d16d-11e4-8969-6a88dd715fd3.PNG)

At 1, that is the direction provided. "Ours" (2) is using "getOpposite()" while "Theirs" (3) is using "getFront()". 

From EnumFacing:
    /**
     * Get a Facing by it's index (0-5). The order is D-U-N-S-W-E. Named getFront for legacy reasons.
     */
    public static EnumFacing getFront(int index)
    {
        return VALUES[MathHelper.abs_int(index % VALUES.length)];
    }

You are passing the value of the int as opposed to the opposite. If I may make a suggestion, instead of going "for(int i =0; i < 6; i++)" and using your block helper, just use "for(EnumFacing facing : EnumFacing.values())" and use "worldObj.getTileEntity(pos.offset(facing))" to get the tile in that direction. You can also just call facing.getOpposite() to pass the opposite into the receiver.  This is what minecraft and forge want in 1.8.

**Comment by Vanhal** [comment]
Sure why not. I don't actually use the facing anyway so it doesn't effect me. Fixed in 1.6.4
