### ISSUE TITLE
Generators not accepting fuel input from any side - PA version 1.6.4 w/MC 1.8

### ISSUE THREAD

**Issue by liftoff** [Vanhal/ProgressiveAutomation#105]
I'm running PA 1.6.4 in Minecraft 1.8 w/Forge 1.8-11.14.1.1341 (no other mods).  Progressive Automation generators are not accepting fuel input from any side via chests, hoppers, etc.  I tried them all (wood, stone, iron, diamond).

**Comment by Vanhal** [comment]
Weird... It is working for me. (Except from the top but that was to be expected)
It's not going to automatically pull from the likes of chests and thing. But hoppers should work.

See what mode the sides are in using query mode on the wrench. The only modes that will work are Normal and FuelInput (input won't work).

**Comment by liftoff** [comment]
Aha!  I just needed to use the wrench to set the side to FuelInput.  I had no idea you had to do that for it to work.  Seems like that should be the default mode, no?

Also, why doesn't it accept fuel input from the top?

**Comment by Vanhal** [comment]
They should accept fuel on normal mode too, which is the default. Due to the way it's coded all the machines have a default output side, which is the top, which is why they don't accept from the top. I've changed that in 1.6.5 so that it should work without having to reconfigure any sides!! :+1:

**Comment by liftoff** [comment]
Awesome, thanks for the help and for making a great mod!
