### ISSUE TITLE
Feature Request: Add support for Random Things' Fertilized Dirt to the planter

### ISSUE THREAD

**Issue by liftoff** [Vanhal/ProgressiveAutomation#106]
The planter doesn't seem to work with the Fertilized Dirt from the Random Things mod...

https://randomthingsminecraftmod.wikispaces.com/Fertilized+Dirt

The interface just says "Waiting..." forever when trying to use Fertilized Dirt instead of regular dirt.  I assume it's because the planter has a hard-coded block ID for dirt?

Anyway, it would be nice if the planter supported Fertilized Dirt because it really is a nice (non-OP) thing from the Random Things mod.

**Comment by Vanhal** [comment]
Now that's something I thought I had added. Will get that added asap
