### ISSUE TITLE
Some Ticon tools aren't working quite right 

### ISSUE THREAD

**Issue by jadedcat** [Vanhal/ProgressiveAutomation#107]
http://minecraft.curseforge.com/forums/jadeds-packs/agrarian-skies-2/773-agskies-2-alpha-bugs?comment=330

Summary of the post:

- TiCon tools keep working in machines after they are broken.
- TiCon tools don't get xp in machines - I like this, please don't change?
- Cobble Gen doesn't use fuel

**Comment by Vanhal** [comment]
TiCon Tools are ejected from the machine once they are broken.
Cobble gen only generates cobble when the machine is working and using power.

Tools will continue to not gain xp!
