### ISSUE TITLE
PAWrench causes problems with "Better Chests" chests

### ISSUE THREAD

**Issue by MikeSingularity** [Vanhal/ProgressiveAutomation#117]
I accidentally tried to open a "Better Chests" chest with the wrench on Rotate mode.  It rotated the chest and a

ll items and upgrades in the chest were lost.  Seems to happen every time the wrench is used this way.

Minecraft Version: 1.8
Forge Version: 11.14.1.1334
Aroma1997Core: 1.0.3.4
BetterChests: 1.2.0.0
Progressive Automation: 1.6.4

Better Chests mod:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287828-aroma1997s-mods-betterchests-mining-world-mod

Here's a log: http://pastebin.com/Fj4tuSmd

**Comment by Vanhal** [comment]
I'm just calling rotate on the target blocks, i suspect the issue is on Aromas side.
