### ISSUE TITLE
Transmitted RF from Flux Ducts no longer charges RF Engines

### ISSUE THREAD

**Issue by MikeSingularity** [Vanhal/ProgressiveAutomation#118]
After upgrading to 1.6.4, flux ducts no longer carry RF from generators to machines.  Existing, working configurations as well as new configurations are broken.  Specifically the RF engine is no longer being charged, once depleted, the machine stops working.

When I revert to Progressive Automation 1.5, the RF Engine charges and the machine starts working again.  I've experience the problem with the crafter and chopper, I haven't tested other machines.  All of my RF engines were crafted under 1.5, I didn't test crafting a new engine.

Versions:
Minecraft Version: 1.8
Forge Version: 11.14.1.1334
Flux Ducts: 1.0.1
Progressive Automation: 1.6.4

**Comment by Vanhal** [comment]
I think I switched the facing side in 1.6.4... I'll ping Fyber and see if switching that will fix it.

**Comment by FyberOptic** [comment]
I'm glad this came up.  When I made Flux Ducts I did feel that the direction seemed a bit backwards.  But it was my first attempt at implementing RF, and I remembered a time during Redstone Paste when there was a certain vanilla function which was indeed directionally backwards, so it wasn't the craziest thing I'd ever seen.  I just went with what worked.  So it's good to know that it was just a simple bug and not a misleading API.

I'll see if I can get on this later today and get a new version out.

**Comment by Vanhal** [comment]
Hahha. Yeah someone else wrote a huge long issue on how it was backwards which made a load of sense. https://github.com/Vanhal/ProgressiveAutomation/issues/103

I comes from the fact that ForgeDirection is actually backwards to ENumFacing and my direct conversion didn't actually make sense.

**Comment by FyberOptic** [comment]
[Okay, flipped the directions, seems to work fine now.](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2379480-flux-ducts)
