### ISSUE TITLE
Feature request: above diamond tools

### ISSUE THREAD

**Issue by jadedcat** [Vanhal/ProgressiveAutomation#121]
For some reason the diamond miner in AS2/MF3 packs does not like the TiCon tools that are higher level than diamond. Not sure if its intentional or not.

**Comment by Vanhal** [comment]
Weird. It should... I'll try it out with the configs from AS2

**Comment by Vanhal** [comment]
ohhhh.... Any idea on what the max mining level is for the later tools?

**Comment by Vanhal** [comment]
Figured it out. Fixed in next version.

**Comment by jadedcat** [comment]
I know you closed it, but if it helps, the highest mining level I have seen was 99

**Comment by Vanhal** [comment]
Yeah.... That would DEFINITELY explain it :D I was never excepting one higher than 10 which is why. It's now set to 100 instead. Up on curse 1.6.14
