### ISSUE TITLE
List of Tools that can't be used in the miner

### ISSUE THREAD

**Issue by Badcholo** [Vanhal/ProgressiveAutomation#123]
I can't use these tools in the Miner

ALIENS VS PREDATORS Mod tools

Super Diamond Tools mod

Thermal foundation:
Lead Pickaxe
Ferrous Pickaxe
Invar Pickaxe
Electrum Pickaxe
Silver Pickaxe
Tin Pickaxe
Bronze Pickaxe

**Comment by Vanhal** [comment]
Thermal foundation tools should all work >= 1.6.15
