### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by Badcholo** [Vanhal/ProgressiveAutomation#125]
I am creating custom textures for your mod and i would like to know if you want to have them.
I would like to help any way i can. Please let me know if you want 32x32 or 16x16 textures. I have never made a mod and i have no idea how the textures are used. I have MCreator and i can make custom textures atm, here is a preview of my first block. I'll change it up a little bit and make it look really nice. Please let me know if you like it or how to make it better
![2015-04-23_21 29 46](https://cloud.githubusercontent.com/assets/10932905/7312491/fc40ae62-e9ff-11e4-9609-5e602e39d547.png)
![2015-04-23_21 30 05](https://cloud.githubusercontent.com/assets/10932905/7312492/01eac762-ea00-11e4-8ff0-6653b45d58d5.png)

**Comment by Badcholo** [comment]
i made more in 32x32 if you like
![2015-04-23_23 06 32](https://cloud.githubusercontent.com/assets/10932905/7313387/896f99bc-ea0d-11e4-8833-c970057c13f0.png)
![2015-04-23_23 06 10](https://cloud.githubusercontent.com/assets/10932905/7313389/8d5bf8f4-ea0d-11e4-9f47-aa952cd2ee80.png)

**Comment by Badcholo** [comment]
I am willing to make textures for all your machines if you like, just let me know. I just want to help

**Comment by Vanhal** [comment]
A load of other people have created texture packs that include this mod. You should look into how to do that.

**Comment by Badcholo** [comment]
I didn't want to force my players to use a specific texture or resource pack. i figured it would be better to add the textures to the actual blocks. I guess you have a Load of other people so i guess you don't need my help.
