### ISSUE TITLE
Chopper not picking up tree...

### ISSUE THREAD

**Issue by ericBG** [Vanhal/ProgressiveAutomation#126]
I've got a stone chopper with a range upgrade on it, and it still won't pick up a tree that is diagonally adjacent to them:

![2015-04-24_07 43 26](https://cloud.githubusercontent.com/assets/3256815/7313850/efcd600c-ea55-11e4-8327-fecab73094d0.png)
![2015-04-24_07 43 22](https://cloud.githubusercontent.com/assets/3256815/7313851/efcf8d6e-ea55-11e4-819a-670e421ce448.png)

**Comment by Vanhal** [comment]
You need 2 upgrades to go all the way around in AgSkies2 (see image) and you would need 7 upgrades normally.
[img]http://puu.sh/h9niV/e4737afa1c.png[/img]

**Comment by ericBG** [comment]
Oh I understand. Maybe a range show tool would be quite nice, because I automatically assumed it was a radius as upgrades tend to be. Thanks for the explanation.

**Comment by Vanhal** [comment]
Yeah I've been trying to figure out how to show the range but it's proving difficult.

**Comment by ericBG** [comment]
You can maybe do it like OpenBlocks' building guide does it? Their code is open source so you can access it here: https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/tileentity/TileEntityGuide.java#L189-193 (I've highlighted the lines that I think do the rendering of the ghost blocks)
