### ISSUE TITLE
Incorrect `TileMiner.isDone` computation when no tool present

### ISSUE THREAD

**Issue by fnuecke** [Vanhal/ProgressiveAutomation#127]
When a miner is missing a tool, the number of blocks that can be mined gets computed based on that. This leads to the number of mineable and mined blocks to be identical, thus `isDone` reports `true`, and thus a redstone signal is being emitted. This in turn will disable hoppers feeding tools into the miner. It took a friend and me embarrassingly long to figure out the problem was the redstone signal emitted by the miner >_> (I even attached a debugger to the server...)
I'd suggest adding a check for tool presence in `isDone`, i.e. return `false` if no tools are in the miner? That seems to be the easiest solution, anyway. Otherwise maybe use of a "default tool", equivalent to the best tool that can be placed in the miner, for the `canToolHarvestBlock` checks, if none is in the inventory?

**Comment by Vanhal** [comment]
Ugh, that's a bit of an oversight on my side. I'll get that fixed up.

**Comment by Vanhal** [comment]
Fixed this in version 1.6.15

**Comment by fnuecke** [comment]
Awesome, thanks! :-)
