### ISSUE TITLE
Iron Planter not accepting Iron Hoes

### ISSUE THREAD

**Issue by kreezxil** [Vanhal/ProgressiveAutomation#128]
but it does accept lesser hoes

**Comment by Vanhal** [comment]
Version? Pack?

**Comment by kreezxil** [comment]
My bad, using version 1.8-1.6.4 on Forge Dedicated Server b1392

**Comment by Vanhal** [comment]
Ah yeah, I fixed that issue in the 1.7 release. I'll pull the 1.8 up to the latest version.

**Comment by kreezxil** [comment]
cool

**Comment by kreezxil** [comment]
another thing, does the planter act on items that extend class iPlantable?

**Comment by kreezxil** [comment]
like the corn from techstack's heavy machinery mod. http://minecraft.curseforge.com/mc-mods/228320-techstacks-heavy-machinery-mod

**Comment by Vanhal** [comment]
It should do, except saplings.

**Comment by Vanhal** [comment]
Fixed in version >= 1.6.15
