### ISSUE TITLE
Planter (and probably other machines) Ignoring NBT when checking for resources

### ISSUE THREAD

**Issue by bonii-xx** [Vanhal/ProgressiveAutomation#129]
The planter ignores NBT when moving items from his right-side inventory to his left-side seed-slot.

Easiest way to reproduce: Take two Agricraft seeds with different stats. Put the one you want into the seed slot and the 2nd one to the right. It'll increase the stacksize on the left although the NBT doesn't match.

**Comment by Vanhal** [comment]
Ugh, isItemEqual doesn't compare tags that's nice to know. Fixed version >= 1.6.15
