### ISSUE TITLE
Animal Farmer ignores cooldown on cows when milking

### ISSUE THREAD

**Issue by bushbaby1234** [Vanhal/ProgressiveAutomation#130]
in version 1.6.14 installed in Agrarian Skies 2 version 1.0.37a the animal farmer ignores the cooldown on cows when milking.

**Comment by Vanhal** [comment]
Considering it is using a fake player to right click with the bucket I find that unlikely....

**Comment by bushbaby1234** [comment]
just checked again. im using a stone animal farmer and it is milking once every second. i thought the cooldown was like 5 mins

**Comment by Vanhal** [comment]
It's 5 minutes for breeding them. I just went into a new world with 16 buckets and spammed right click on a cow and there was no cool down as far as I could see.

**Comment by bushbaby1234** [comment]
weird i cant do so on ag skies, and if i try the cow makes a displeased mooing noise. maybe jaded added a cooldown on the cow. and if so it is bypassing that.

**Comment by Vanhal** [comment]
OH! Hahaha. That's that mod she uses to make animals dislike you! I've no idea how I hook into that I'm afraid.

**Comment by bushbaby1234** [comment]
lol! well now you know.
