### ISSUE TITLE
1.8-1.6.15 doesn't hoe or plant

### ISSUE THREAD

**Issue by kreezxil** [Vanhal/ProgressiveAutomation#131]
It just says waiting in the gui, but at least it accepts the iron hoes now. also the console is outputting no errors.

![2015-04-28_11 19 01](https://cloud.githubusercontent.com/assets/3880072/7373120/5923fd30-ed90-11e4-934f-56a553a51763.png)
Not tilling any land. and also not planting anything. Is it too close to the tree farmer? Note: I manually tilled the one block and it didn't plant anything on it. I previously had corn from TechStack's Heavy Machinery in it. He said that it extended iPlantable. Now there are seeds in the machine as can be seen below, just waiting, doing nothing.
![2015-04-28_11 24 45](https://cloud.githubusercontent.com/assets/3880072/7373268/046560bc-ed91-11e4-8880-9d82921bf18d.png)

This all on a Dedicated Forge server b1397 (SMP).

**Comment by Vanhal** [comment]
Planter goes under the soil....

**Comment by kreezxil** [comment]
Ok thanks

-----Original Message-----
