### ISSUE TITLE
Cross-Mod issue

### ISSUE THREAD

**Issue by micheldewit** [Vanhal/ProgressiveAutomation#132]
Goodday sir, 
hereby a bug report; 
Conflicting mods: 
Agricraft + Progressive Automation. 
Detailed Explainations: 
it seems to be working on the first glance: It is implementing the seeds properly on the sticks.
It doesnt work with Agricraft Sugarcane seeds tho; It removed the sticks altogether and places the sugarcane seeds on vanila method back.

**Comment by Vanhal** [comment]
This is possibly because agricraft sugarcane needs to be on sugar?
I'm not sure how I can check the valid soils but I've made it so that it's not going to waste the seed if the soil isn't valid.

**Comment by micheldewit** [comment]
No, agricraft needs sugarcane "Seeds" to be placed on sand + sticks, but for some reason, the sticks are removed by PA and places the sugarcane directly onto the sand, which makes it unusable for crossbreeding and the seeds are lost in progress

**Comment by Vanhal** [comment]
Yeah I tired that and it worked fine for me....

**Comment by micheldewit** [comment]
Maybe an good idea to inform you which MP I am using: 
Agrarian Skies 2.

**Comment by Vanhal** [comment]
Seems to be working fine for me in AgSkies2.....
![2015-05-01_19 48 53](https://cloud.githubusercontent.com/assets/7526890/7435381/2f26c672-f03b-11e4-95c3-bb3b2a6d9973.png)

**Comment by micheldewit** [comment]
Bonemeal it up, and then see it bug up!

**Comment by Vanhal** [comment]
Seems to be fine for me.... Maybe check your progressive automation settings and make sure that AgriCraft Compat is set to true.
![utopia3_1](http://giant.gfycat.com/ActiveAcclaimedGemsbuck.gif)
