### ISSUE TITLE
Magical Crops issue

### ISSUE THREAD

**Issue by azzgazz** [Vanhal/ProgressiveAutomation#134]
I put a weak infusion stone for Magical Crops in the wooden crafter to craft Accio Essence. As soon as the crafting process completed, my server crashed. I had to remove/re-add mod to fix

http://pastebin.com/8seYmdT0

**Comment by Vanhal** [comment]
I thought I had fixed this issue! (I suspect the issue is actually with magical crops but I'll check it out)

**Comment by ProRedHD** [comment]
It doesn't look like this crash has anything to do with PA. Some kind of Issue with MineTweaker and MineFactoryReloaded's Fuel Handler.
