### ISSUE TITLE
Range is counterintuitive

### ISSUE THREAD

**Issue by Nagapito** [Vanhal/ProgressiveAutomation#140]
Hi,

Like most of the machines in Minecraft, range is supposed to be the diameter around the machine. So.. a range of 3 should affect +1 block in every direction or a 3x3, a range of 5 a 5x5 and so on...

Your implementation of range is strictly the area of effect, so it needs a range of 9 to do a 3x3. That is very counter intuitive and most of players will not understand what's happening.

I had to look at your code to understand what was going on with my miner, since he was only mining 7 blocks instead of 7x7 area that I was expecting!

Maybe the tooltips should be more specific if you really want the area or...just change it to diameter.

**Comment by Vanhal** [comment]
It's the way it's designed to be.

**Comment by Nagapito** [comment]
I figured it would be the way you want it to be, since its not a bug in the code, its coded to work that way.
But... it really needs something to explain what is going on or people will think its broken and not use it.

**Comment by Vanhal** [comment]
yeah i'm not good at adding rendering. I wanted to add something like the mfr range overlay but don't honestly don't know how to do it.

**Comment by Nagapito** [comment]
Just had a tooltip on NEI saying its the number of blocks... Or change the 'range' word. The whole problem comes from this word, its not range, since in a 2D plan, range means an area, all blocks in X range of the machine...
