### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cauliflower69** [Vanhal/ProgressiveAutomation#141]
We recently started hosting some Agrarian Skies 2 servers and one thing we would really like implemented is that the machines don't drop the items on the ground when it is full. 

This has caused some hard TPS issues. Maybe have a void upgrade or the machine just stops when its full but still consumes the fuel ?

Fantastic mod by the way, nice to see a fellow Irishman making cool mods

**Comment by Vanhal** [comment]
hmmm, I did originally have it that way so it should be possible to add that in as a config. I'll see what I can do.

**Comment by cauliflower69** [comment]
Wow that was fast! Thanks so much
