### ISSUE TITLE
Dependencie Issue TConstruct + Progressive Automation + Ex Astris

### ISSUE THREAD

**Issue by ppvolto** [Vanhal/ProgressiveAutomation#143]
Following bug appears when using TConstruct, Progressive Automation and Ex Astris without CoFHCore in the pack since its appears to be in the Init sequence of Progress Automation i report it here.

Crash Log:
http://pastebin.com/LX13K5sr

**Comment by Vanhal** [comment]
So I bumped the version of COFH lib i'm using to match ex astris. It should work though I'm not sure why it wouldn't....

**Comment by ppvolto** [comment]
I have Tried a Custom Build for 10.3.1384 in forge since that was the min requirements of a other mod after that the Bug do not disappear but after i moved the cofh folder from src/main/java to src/api/java it disappeard...
