### ISSUE TITLE
Empty buckets cannot be piped out of the fuel slot

### ISSUE THREAD

**Issue by KaiserYoshi** [Vanhal/ProgressiveAutomation#144]
There is no configuration that allows items to be retrieved from the fuel slot of machines (tested with planter, chopper, and animal farmer), so the use of lava buckets as fuel cannot be automated.

If a "fuel output" mode is out of the question, this could be worked around by having machines move the bucket to an output slot after consuming the lava.

Progressive Automation 1.6.18
Forge 10.13.3.1387
Minecraft 1.7.10

**Comment by Marcelo-Petrucelli** [comment]
I don't understand why this was closed. @ItsTheKais is correct.
