### ISSUE TITLE
[1.8-1.6.15] Planter doesn't work right with sugar cane

### ISSUE THREAD

**Issue by KurikAmudnil** [Vanhal/ProgressiveAutomation#147]
when trying to use the planter with sugar cane, the initial planting works, but then it stops waiting every few seconds to try to plant another.  It fails to plant, but consumes a seed anyway.  When the cane grows (or I place a second cane on top), the planter takes a second or so to break it, but the item frequently falls to the ground instead of being harvested (suggesting that the bottom one was broken and replanted instead).  Cactus seems to work just fine

**Comment by Vanhal** [comment]
What's you set up like?

**Comment by KurikAmudnil** [comment]
My intitial setup is a row of water + 2 rows of dirt + row of water + 2 rows of dirt + row of water + 2 rows of dirt, creating an 8x8 space (or 10x8 including outside water edges) of 48 plant-able spaces , the planter underneath is of the wood variety with range of 64, and I put lily pads on top of the water.  Initial planting works just fine, but it continually consumes the seed stock without replentishing from growth, and the output doesn't gain any harvest either

My test setup is a 3x3 with the center square a water source.  I tested with and without the lily pad, I removed the auto output.  I also tested with a default range one with a water source to the south.

**Comment by KurikAmudnil** [comment]
mod setup, lots of mods but none should affect sugar cane.. 
forge-1.8-11.14.3.1468,  optifine, Liteloader #45, Progressive Automation was 1.6.4 (upgraded to 1.6.15 to see if problem persists), voxel map, ... "dir /w /b mods > modlist.txt" :  http://pastebin.com/nZ5AcqUD

**Comment by Unatan63** [comment]
Noticed the posting date is a little old but the Sugar Cane aspect of this mod doesn't seem to be working right, the planter eats any cane is harvests, am running FTB Unstable v3.015 and have my sugar cane farm with an Iron Planter, doesn't matter how many upgrades one uses, it plants the cane but eats what ever it harvests, the other farms (wheat, carrot and potato) all work fine

**Comment by Vanhal** [comment]
Should be fixed in the newest 1.8.9 version (kinda)
