### ISSUE TITLE
Power Advantage

### ISSUE THREAD

**Issue by cyanobacterium** [Vanhal/ProgressiveAutomation#148]
Hi Vanhal,

I'm DrCyano, author of the [Power Advantage API](https://github.com/cyanobacterium/PowerAdvantageAPI), and I want to add compatibility between the power systems of your mod and Power Advantage.

There are three ways we can do this. Method one would be for me to create a converter block that accepts Power Advantage energy types and outputs the energy type (RF?) used in your mod. Method two is that you could use the Power Advantage API yourself and convert your base machine class to be a simple power consumer (Power Advantage API can do the rest). Method three is that I could try to do the conversion for you and hand you a pull request, but then I'd need to know a little more about how your mod works under-the-hood and I might make changes that you don't like to facilitate compatibility.

Let me know what you prefer,
-DrCyano

**Comment by Vanhal** [comment]
I think your best bet would be to make a converter block. I know there are a few other 1.8 mods out there that are using the RF API that I'm using so for increased compat across them it might be the best way.

**Comment by cyanobacterium** [comment]
I'm currently working with Fnuecke from the OpenComputers mod to create a lightweight interface for easier integration (see issue thread [here](https://github.com/MightyPirates/OpenComputers/issues/1248#issuecomment-116002487) ). If I also add a RF converter, how do I use the unofficial RF API without causing a duplicate class error when multiple mods with the same RF API classes launch at runtime?

**Comment by cyanobacterium** [comment]
I've added a light-weight API to make it easier to support Power Advantage without rewriting any of your machine or block classes. See the release page for [Power Advantage API v1.2.0](https://github.com/cyanobacterium/PowerAdvantageAPI/releases/tag/v1.2.0) for an example. If that doesn't suit you, I've implemented an RF interface, but it is untested and could crash the game if you have complicated RF machines that don't expect power to come at them from random directions.

**Comment by twothe** [comment]
I don't see any particular reason for yet another Power API. I think the easiest way for you is to just add RF compatibility to your machines, which - thanks to the examples - is a pretty easy thing to do.

**Comment by Soultron** [comment]
If may interject.  Power Advantage is the only full fledged power mod for 1.8.  It does not even exist for 1.7.10.  I would actually ask @Vanhal here if he felt that the RF API port was even complete. 

"The Redstone Flux API has not been officially updated to Minecraft 1.8."
  -FyberOptic
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2379480-flux-ducts

 @cyanobacterium has already provided us with a rudimentary RF adaptation.  However using the lightweight API is FAR more CPU friendly.

**Comment by twothe** [comment]
I took a look at your sources, and as a summary it was of low quality, had several significant bugs and shows a lack of understanding of programming in Java. And especially I could not see any reason this should be "FAR more CPU friendly".

I am pretty sure you are riding a dead horse here.

**Comment by cyanobacterium** [comment]
Whoa, guys! Keep it clean and don't be haters.

Power Advantage is a Block oriented power API whereas RF is a TileEntity oriented API. The big difference being that power cables in Power Advantage do not have tile entities (hence the claim for reduced CPU load for large cable networks). This difference is also the reason the interface for supporting RF is a little clunky (there's no easy way that I know of to determine the class of tile entity generated by a given block during initialization).

If that doesn't interest you, Twothe, I'm cool with that, but there are a number of users who love both of our mods and we will continue to receive requests for tighter integration.

**Comment by twothe** [comment]
For some strange reason people always consider a negative professional summary "hating". Anyways: end of discussion from my side.

**Comment by cyanobacterium** [comment]
A pleasure doing business with you.
