### ISSUE TITLE
Stone Killer Glitch/Bug

### ISSUE THREAD

**Issue by ShadowLightStuff** [Vanhal/ProgressiveAutomation#149]
Greetings!

As the title implies, I seem to be having issues with using a stone killer on Agrarian Skies 2. One of the quests on this mod pack involves making a stone killer. I can make the killer just fine, but what I cannot do is use it. You see, when I go to add a Stone Sword in, it doesn't work (presumably because Jadedcat saw to it to make vanilla swords as useful as "wet noodles"). I tried using Tinkers Construct tools, but those don't want to go in...

Anywho, I'm not sure what is going on. Is it an incompatibility between mods? Or is it something else?

**Comment by ShadowLightStuff** [comment]
The upgrade filters go in just fine. The weapons, however, do not.

**Comment by Vanhal** [comment]
There is a bit of a issue between Progressive Automation and Iguana tweaks. I'm going to be making some changes to help with that.
You should be able to put a TiCo sword into the killer as long as the "level" of the sword is less than stone (So flint, bone, cactus and stone).

**Comment by ShadowLightStuff** [comment]
Thanks!
