### ISSUE TITLE
Tool recipes don't use ore dictionary for sticks

### ISSUE THREAD

**Issue by twothe** [Vanhal/ProgressiveAutomation#151]
I noticed a minor issue when using Progressive Automation together with Natura: the recipes for the Wither tools do not use the ore dictionary for sticks, so only vanilla wooden sticks work.

They should use ore:stickWood instead.

**Comment by Vanhal** [comment]
...I never thought there would be sticks.... I'll add that.

**Comment by Vanhal** [comment]
Looking at this the recipes are using ShapedOreRecipe so they should be using the ore dict version of sticks if they exist.

**Comment by twothe** [comment]
Using the ShapedOreRecipe is only step one. You need to actually use the ore dictionary strings in the recipe like this: 
```Java
    final ShapedOreRecipe recipe = new ShapedOreRecipe(new ItemStack(this, 8), 
      "ppp", 
      "pnp", 
      "ppp", 
      'p', "logWood",     // instead of Blocks.log
      'n', Items.nether_star
    );
```

**Comment by Vanhal** [comment]
Weird! I actually have that down for the logs, but for some reason I assumed that it automatically replaced items and blocks if they have an ore dict entry. I'll fix that now.
