### ISSUE TITLE
Miner Game Balance Problem

### ISSUE THREAD

**Issue by Fluffkin** [Vanhal/ProgressiveAutomation#152]
Short version:
The miner digs all the blocks and damages the pickaxe for every block. In an average world (modded or not) this means pickaxes get used up faster than the miner finds the ores / gems to make new pickaxes.

Normal mining (by hand), you dig a staircase and side runs, then only dig out the ores / goodies you find, so the ratio of junk block to ore damage is something like 60% clearing, 40% ores. The miner makes it more like 95% clearing, 5% ores = it's useless as a miner.

Suggestion: Add a % chance of damage to pickaxe for each block dug to the config file. Start it around 50% damage to pickaxe (as a guess for a default). Then see if it tends to get you slightly more ore than it's using up in picks. Tweak as required.

**Comment by twothe** [comment]
Aside from other mods, there are Wither tools in Progressive Automation that you can use to create (close to) unbreakable tools.

Additionally you can put the Miner further down, e.g. y=16 (where the diamonds start) to avoid wasting durability on cobble.

**Comment by Vanhal** [comment]
I haven't had a chance to do some testing properly on this but twothes suggestions are good.

You can also enchant the tools, unbreaking will basically do what you're describing. And what I do when I'm mining is put stone pickaxes into the iron miner, wait for it to be done then put an iron pickaxe. The stone pick will do all the stone and iron and the machine won't do those blocks again once you put the iron pick in.
