### ISSUE TITLE
Chopper is unable to plant Forestry saplings

### ISSUE THREAD

**Issue by twothe** [Vanhal/ProgressiveAutomation#154]
The Chopper will accept saplings from Forestry, but won't plant them.

![forestry](https://cloud.githubusercontent.com/assets/1131621/8711415/fbf24766-2b51-11e5-8f3d-b3b832582119.jpg)

**Comment by Vanhal** [comment]
This one is very strange. I did test the chopper with forestry saplings and there should be no reason that they are not being planted. I'll have a look and see if I can figure it out.

**Comment by twothe** [comment]
I was using unidentified saplings I found in a villager's chest. I have not tried any other saplings so far.
