### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nicky8009123** [Vanhal/ProgressiveAutomation#155]
Would it be possible to make it so if you put a tool that needs RF to be used in a machine with an RF engine, The tool would be charged as well as the machine? I can't seem to find a way to pull out my sword and recharge it for the killer.

**Comment by Vanhal** [comment]
It would be possible but I probably won't be doing it. I agree that there needs to be a way of pulling tools out though, I'll bee about changing that.
