### ISSUE TITLE
Chopper has trouble with Acacia trees

### ISSUE THREAD

**Issue by twothe** [Vanhal/ProgressiveAutomation#157]
The chopper sometimes does not properly recognize the extension of Acacia trees and ignores parts of it when chopping. This effectively renders automated Acacia tree farms unusable after some time, as the remaining parts block further tree growing.

The chopper in this image considers this completed and is waiting for new trees to grow, which will probably never happen.
![acacia](https://cloud.githubusercontent.com/assets/1131621/8747637/ee75450e-2c94-11e5-9e25-6bfc684b0118.jpg)

**Comment by Vanhal** [comment]
Yeah it's because of the silly diagonals! The searching algo only looks to the cardinal directions (and up) for more of the trees. I've tried playing around with it a bit before but I might have another look.

**Comment by twothe** [comment]
As far as I can tell from the code the problem seems to be that you only search for adjacent blocks to the current chopping block. I'd suggest trying a 3x3x3 cube top->down instead, this might solve the issue.
