### ISSUE TITLE
Miner won't output to chest

### ISSUE THREAD

**Issue by Booyakka** [Vanhal/ProgressiveAutomation#160]
In the most recent version of Obscurity (V 1.1.14) in the FTB launcher the miner and chopper ignore all inventories placed above them. Chests, barrels, item conduits, extraction pips and strongboxes all have failed. Items are just ejected from the top. Wrenching the sides to change their behavior also has no effect.

**Comment by Vanhal** [comment]
Issue was already fixed in version 1.6.21
