### ISSUE TITLE
Crafter Issue

### ISSUE THREAD

**Issue by ThexXTURBOXx** [Vanhal/ProgressiveAutomation#164]
If I place a Stone Crafter (not tested with iron, diamond or wood ones) and connect a EnderIO Itemconduit it can input into the crafter, but I can't get it working on outputting. It will only output out of the 3x3 field (which is the input). I have tested it on every side of the crafter, but everytime it outputs out of the right 3x3 field.

**Comment by Vanhal** [comment]
If I remember correctly only the bottom side is defaultly configured for the output slot. Use the wrench to configure which side you want to be the output

**Comment by ThexXTURBOXx** [comment]
Ok, I will check tomorrow, if that works. If it works, sorry for my stupidity :D
