### ISSUE TITLE
Killer damage level

### ISSUE THREAD

**Issue by defakto** [Vanhal/ProgressiveAutomation#165]
Attempting to use the killer and regardless of the sword type in it, it always does 1/2 heart of damage.

**Comment by Vanhal** [comment]
Yeah I'm aware of this issue. I'm not entirely sure how to fix it yet though.

**Comment by NolanSyKinsley** [comment]
I really want to find a solution for this. This bug pretty much makes the killer useless. Killing mobs 1/2 heart at a time and the weapon taking 1 durability hit each time means that it is simply too slow and too expensive to use.
