### ISSUE TITLE
Miner extracts wrong ores

### ISSUE THREAD

**Issue by NoX-programer** [Vanhal/ProgressiveAutomation#170]
When using any pickaxe with silk touch ench, miner extracting ore with id X:Y as X:0, i.e. cuts the metadata. It is critical when we have mods using same id for many ores, such as Thermal Expansion (Foundation) and Tinker's Construct.

Version: ProgressiveAutomation-1.7.10-1.6.24

**Comment by Vanhal** [comment]
Legitimately confused as how no one has reported this before...
