### ISSUE TITLE
1.7.10 MC fatal error - rendering something in RA

### ISSUE THREAD

**Issue by MoonCutter2B** [Vanhal/ProgressiveAutomation#171]
This crash has started to happen every now and then. Maybe since last update of RA.
link to forge log:
https://dl.dropboxusercontent.com/u/58751759/fml-client-latest.log
link to MC log:
https://dl.dropboxusercontent.com/u/58751759/crash-2015-08-04_05.26.34-client.txt
always the same exception.

**Comment by Vanhal** [comment]
Hopefully b90a43b fixed this. If it didn't please reopen!
