### ISSUE TITLE
Iron Miner

### ISSUE THREAD

**Issue by GamingWithAGoose** [Vanhal/ProgressiveAutomation#172]
When using the Iron Miner it just spits all of the blocks that it has mined out of the top. I've used a PA Wrench to change the output side, I've put chests directly next to the top and any other output side and I've tried piping the blocks out of every side as well but to no avail. I know this is probably a problem on my end and if it is please could someone tell me what I've done wrong.

**Comment by Vanhal** [comment]
What version are you using?

**Comment by GamingWithAGoose** [comment]
Im not 100% sure, whatever version is the latest for the obscurity modpack.

**Comment by Vanhal** [comment]
I think you're 1 behind, where i fixed that bug
