### ISSUE TITLE
Machines don't fill the internal inventory

### ISSUE THREAD

**Issue by ScarleTomato** [Vanhal/ProgressiveAutomation#175]
Tried out the chopper and the miner with the Obscurity pack. The machines I guess think that the inventory is full for some reason. I'm guessing this is an issue with one of the other mods but I haven't narrowed down what the cause is yet.

You can see an example here https://youtu.be/5MfN-I_ZppE?t=382 (Scary music for a scary bug!)

**Comment by Vanhal** [comment]
Update to newest version.

**Comment by ScarleTomato** [comment]
Works thanks! Sorry I didn't see that there was a newer version. Really liking this mod!
