### ISSUE TITLE
Animal Farmer dupes items when full

### ISSUE THREAD

**Issue by LyraelRayne** [Vanhal/ProgressiveAutomation#177]
When an animal farmer is full and it attempts to further collect an item (for example an egg or wool) the farmer will spit the item out. That's fair enough. But a certain percentage of the time it instead spits *two* of that item out. I tested this under the following conditions:

* Fresh curse launcher profile with forge 10.13.4.1448 (MC1.7.10)
* Progressive Automation 1.6.27
* Placed one diamond farmer
* Put blocks of coal into the fuel slot
* Put in a stack of diamond upgrades (probably not necessary)
* Fill the farmer with eggs
* Drop 16 eggs near the farmer.
* Pick up more than 16 eggs

This is made worse when other mods with vacuum hoppers and such are present as the vacuum hopper will pull the item away from the farmer. The farmer will then re-collect it causing a combinatorial explosion of items until the game crashes.

**Comment by Vanhal** [comment]
Sorry for the delay in fixing this, I'll hopefully get time for this next week.
