### ISSUE TITLE
Animal Farmer won't accept wheat

### ISSUE THREAD

**Issue by PmanAce** [Vanhal/ProgressiveAutomation#178]
The animal farmer (all of them) won't accept wheat as input in its input slot. FuelInput works fine.

ProgressiveAutomation-1.8-1.6.15

Thanks.

**Comment by PmanAce** [comment]
Same for carrots and seeds.

**Comment by Vanhal** [comment]
I'll hopefully get to updating the 1.8 version to the newest code next week.

**Comment by PmanAce** [comment]
Thanks a bunch! I really enjoy automating as much as I can and this mod truly helps.

**Comment by Vanhal** [comment]
Should be fixed in the newest 1.8.9 version
