### ISSUE TITLE
Incorrect metadata on galacticraft ore using miner and silktouch

### ISSUE THREAD

**Issue by Vectoresque** [Vanhal/ProgressiveAutomation#179]
I saw the issue on the Galacticraft github that it had happened with another automatic miner and it only seems to happen when loaded with Silk touch tools. when grabbing Galacticraft ores it seems to strip their metadata turning them into different blocks.

**Comment by Vanhal** [comment]
What version are you using? I pushed a fix for this a while back...

**Comment by Vectoresque** [comment]
1.6.16. Sorry, was half asleep and forgot to check to see if i was up to date before posting.

**Comment by Vanhal** [comment]
is it 1.8? I never push the fix for 1.8....

**Comment by Vanhal** [comment]
Should be fixed in the newest 1.8.9 version
