### ISSUE TITLE
Crashed after taking RF Fuel Substituter thing out of machine and then putting it back in

### ISSUE THREAD

**Issue by brandonf1218** [Vanhal/ProgressiveAutomation#183]
Hey Vanhal, I must say i love the mod; It's fantastic. I ran into this issue last night when messing around with my current non-profit and in the works modpack. I was using RF from Power Advantage by DrCyano was filling up one of those RF Fuel Substituter things, it was working perfectly fine! But then i tried to take it out and the game crashed. Here is the crash log 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  SmartCorePlugin (SmartMoving-1.8-16.1.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.96-universal.jar)
  PlayerAPIPlugin (PlayerAPI-1.8-1.3.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  ItemPatchingLoader (ItemPhysic Lite 1.1.3 mc1.8.jar)
  TransformerLoader (OpenComputers-MC1.8-1.5.18.37-universal.jar)
  CCCDeobfPlugin (unknown)
  DLFMLCorePlugin (DynamicLights-1.8.jar)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  LoadingPlugin (ResourceLoader-MC1.8-1.3.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 9/22/15 10:15 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.getMaxEnergyStored(BaseTileEntity.java:887)
	at cyano.poweradvantage.api.modsupport.MaybeRFPowerAcceptor.getEnergyDemand(MaybeRFPowerAcceptor.java:31)
	at cyano.poweradvantage.api.modsupport.LightWeightPowerRegistry.getRequestedPowerAmount(LightWeightPowerRegistry.java:134)
	at cyano.poweradvantage.conduitnetwork.ConduitRegistry.getRequestsForPower(ConduitRegistry.java:113)
	at cyano.poweradvantage.api.PoweredEntity.getRequestsForPower(PoweredEntity.java:171)
	at cyano.poweradvantage.api.simple.TileEntitySimplePowerSource.transmitPowerToConsumers(TileEntitySimplePowerSource.java:192)
	at cyano.poweradvantage.api.simple.TileEntitySimplePowerSource.powerUpdate(TileEntitySimplePowerSource.java:171)
	at cyano.poweradvantage.machines.creative.InfiniteEnergyTileEntity.powerUpdate(InfiniteEnergyTileEntity.java:64)
	at cyano.poweradvantage.api.PoweredEntity.func_73660_a(PoweredEntity.java:96)
	at net.minecraft.world.World.func_72939_s(World.java:1735)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.getMaxEnergyStored(BaseTileEntity.java:887)
	at cyano.poweradvantage.api.modsupport.MaybeRFPowerAcceptor.getEnergyDemand(MaybeRFPowerAcceptor.java:31)
	at cyano.poweradvantage.api.modsupport.LightWeightPowerRegistry.getRequestedPowerAmount(LightWeightPowerRegistry.java:134)
	at cyano.poweradvantage.conduitnetwork.ConduitRegistry.getRequestsForPower(ConduitRegistry.java:113)
	at cyano.poweradvantage.api.PoweredEntity.getRequestsForPower(PoweredEntity.java:171)
	at cyano.poweradvantage.api.simple.TileEntitySimplePowerSource.transmitPowerToConsumers(TileEntitySimplePowerSource.java:192)
	at cyano.poweradvantage.api.simple.TileEntitySimplePowerSource.powerUpdate(TileEntitySimplePowerSource.java:171)
	at cyano.poweradvantage.machines.creative.InfiniteEnergyTileEntity.powerUpdate(InfiniteEnergyTileEntity.java:64)
	at cyano.poweradvantage.api.PoweredEntity.func_73660_a(PoweredEntity.java:96)

-- Block entity being ticked --
Details:
	Name: poweradvantage.infinite_energy_source // cyano.poweradvantage.machines.creative.InfiniteEnergyTileEntity
	Block type: ID #479 (tile.poweradvantage.infinite_electricity // cyano.poweradvantage.machines.creative.InfiniteEnergyBlock)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-207,70,250), Chunk: (at 1,4,10 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #479 (tile.poweradvantage.infinite_electricity // cyano.poweradvantage.machines.creative.InfiniteEnergyBlock)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1735)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: New World-
	All players: 1 total; [EntityPlayerMP['ItzGooby'/609, l='New World-', x=-207.81, y=71.00, z=246.74]]
	Chunk stats: ServerChunkCache: 713 Drop: 0
	Level seed: 1813527267644357075
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -192.00,64.00,252.00 - World: (-192,64,252), Chunk: (at 0,4,12 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2737 game time, 2737 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 61659 (now: false), thunder time: 154819 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 337706280 bytes (322 MB) / 2544893952 bytes (2427 MB) up to 3773300736 bytes (3598 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4048m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1491 Optifine OptiFine_1.8_HD_U_D5 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1491-universal.jar) 
	UCHIJAAAA	Forge{11.14.3.1491} [Minecraft Forge] (forge-1.8-11.14.3.1491-universal.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.96} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.96-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.18.37} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	PlayerAPI{1.3} [Player API] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.2} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAA	SmartMoving{16.1} [Smart Moving] (SmartMoving-1.8-16.1.jar) 
	UCHIJAAAA	AnimalsPlus{1.4} [Animals Plus] (animalsplus-1.4.jar) 
	UCHIJAAAA	ArchitectureCraft{1.0.0} [ArchitectureCraft] (ArchitectureCraft-1.0.0-mc1.8.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.8.x.jar) 
	UCHIJAAAA	basemetals{1.4.1} [Base Metals] (BaseMetals-1.4.1.jar) 
	UCHIJAAAA	bookshelf{2.0.3} [Bookshelf] (Bookshelf-1.8-2.0.3.jar) 
	UCHIJAAAA	CustomMainMenu{1.8} [Custom Main Menu] (CustomMainMenu-MC1.8-1.8.jar) 
	UCHIJAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	poweradvantage{1.2.6} [Power Advantage] (PowerAdvantage-1.2.6.jar) 
	UCHIJAAAA	electricadvantage{1.0.0} [Electric Advantage] (ElectricAdvantage-1.0.0.jar) 
	UCHIJAAAA	eyemod{5.5} [EyeMod] (eyemod-5.5.jar) 
	UCHIJAAAA	fluxducts{1.0.2} [Flux Ducts] (fluxducts-mc1.8-1.0.2.jar) 
	UCHIJAAAA	gnc{0.2} [Gears N' Clouds] (GearsNCloudsv0.2(1.8).jar) 
	UCHIJAAAA	hopperducts{1.4.5} [Hopper Ducts] (hopperducts-mc1.8-1.4.5.jar) 
	UCHIJAAAA	induo{0.3.3} [Induo] (Induo-v0.3.3-mc1.8.jar) 
	UCHIJAAAA	ministrapp{1.8.0-4.1.0} [Minestrappolation Mod] (Minestrappolation-1.8-4.1.0.jar) 
	UCHIJAAAA	modmercenario{1.8} [modmercenario] (modmercenario-0020_1.8.jar) 
	UCHIJAAAA	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8-build1(1.8).jar) 
	UCHIJAAAA	neotech{2.0.5} [NeoTech] (NeoTech-1.8-2.0.5.jar) 
	UCHIJAAAA	OpenComputers{1.5.18.37} [OpenComputers] (OpenComputers-MC1.8-1.5.18.37-universal.jar) 
	UCHIJAAAA	progressiveautomation{1.6.15} [Progressive Automation] (ProgressiveAutomation-1.8-1.6.15.jar) 
	UCHIJAAAA	redstonepaste{1.7.1} [Redstone Paste] (redstonepaste-mc1.8-1.7.1.jar) 
	UCHIJAAAA	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.8-1.3.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (SmartRender-1.8-2.1.jar) 
	UCHIJAAAA	steamadvantage{1.3.3} [Steam Advantage] (SteamAdvantage-1.3.3.jar) 
	UCHIJAAAA	Waila{1.6.0_B1} [Waila] (Waila-1.6.0_B1_1.8.1.jar) 
	UCHIJAAAA	XaeroMinimap{1.6.4} [Xaero's Minimap] (xaeros_minimap_v1.6.4_Forge_1.8.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
SmartCorePlugin (SmartMoving-1.8-16.1.jar)
  net.smart.core.SmartCoreTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.96-universal.jar)
  codechicken.nei.asm.NEITransformer
PlayerAPIPlugin (PlayerAPI-1.8-1.3.jar)
  api.player.forge.PlayerAPITransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
ItemPatchingLoader (ItemPhysic Lite 1.1.3 mc1.8.jar)
  com.creativemd.itemphysic.ItemTransformer
TransformerLoader (OpenComputers-MC1.8-1.5.18.37-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
CCCDeobfPlugin (unknown)
  
DLFMLCorePlugin (DynamicLights-1.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (ResourceLoader-MC1.8-1.3.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ItzGooby'/609, l='New World-', x=-207.81, y=71.00, z=246.74]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
EDIT!
I figured out something, the crash only happens when ever there is continues RF being inserted into the item. If i remove the wire and then take it out and it doesn't crash.

**Comment by Vanhal** [comment]
Crash has to do with poweradvantage, I'm not supporting poweradvantage directly.
