### ISSUE TITLE
Upgrade limit

### ISSUE THREAD

**Issue by gamecraft45** [Vanhal/ProgressiveAutomation#184]
Hello, please add limit (in config) max upgrade use in wood machine and ... It's good thing on server (reduce lags)

**Comment by Vanhal** [comment]
It does only check one block per tick so the size "shouldn't" matter towards lag... Do you have an example?

**Comment by gamecraft45** [comment]
No. I only supposing that can some lag. Only thing what is on this mod bad is this limit upgrades if will be in config I probably use yours good mod in my modpack and on server. Now is little bit hazardous (no are only lags)
