### ISSUE TITLE
Feature Request: Powering machines with Botania Exoflame

### ISSUE THREAD

**Issue by 2bithacker** [Vanhal/ProgressiveAutomation#185]
Just thought I'd toss this in here, but it'd be neat if PA machines could be powered from other mods ways of powering furnaces. In general I'm less interested in the RF methods (such as Immersive Engineering's External Heater) due to the RF engine, but it would be cool if things like Botania's Exoflame worked (being able to power a furnace using mana.)

Of course, it would be pretty neat if all such devices worked (IE External Heater, RotaryCraft's Friction Heater, etc)

Given the PA model of everything using stock fuels, I figured it would fit in pretty well.

**Comment by Vanhal** [comment]
This would definitely be cool! But I suspect that most of these are being done on the other mods side and would require changes to their code. I might be able to get them in with an API on them though. I might have a look into it..

**Comment by Vanhal** [comment]
This doesn't look like it will work.
