### ISSUE TITLE
Replanting Rotarycraft Canola Seeds

### ISSUE THREAD

**Issue by murapix** [Vanhal/ProgressiveAutomation#191]
I tried to use a planter to automate a Rotarycraft canola farm, and while the planter would harvest the crops just fine, it didn't recognize that it could plant the seeds back down. I tested normal seeds as well, to make sure it wasn't a problem with my copy of Progressive Automation, and the planter placed them just fine.

Using MC 1.7.10, and I'm pretty sure using the latest versions of Rotarycraft and Progressive Automation.

**Comment by Vanhal** [comment]
Tested with latest PA and RotaryCraft V9b and it works fine.
