### ISSUE TITLE
Planter doesn't output to a chest above

### ISSUE THREAD

**Issue by DreadBoy** [Vanhal/ProgressiveAutomation#192]
It seems Planter will output any product in chest below instead of above as described on wiki. Is this outdated wiki or bug? I'm using 1.7.10-1.6.27 with Curse Launcher.

**Comment by Vanhal** [comment]
Planter defaults out to the bottom, not the top. You can use the wrench to change the output sides.

**Comment by DreadBoy** [comment]
So, it was problem on my side, thanks for help. :)

**Comment by Vanhal** [comment]
Well the wiki was wrong too, just updated that.
