### ISSUE TITLE
Tinker's Tool Deleted when Output Full

### ISSUE THREAD

**Issue by mellamokb** [Vanhal/ProgressiveAutomation#198]
I've just discovered by accident, that when you are using Tinker's Tool with the Auto-Miner, if there are no empty slots in the output area when the tool becomes broken, it is simply deleted from the world.  I setup 4 auto-miners and left them run for awhile, and when I came back two of them had full output slots and the tinker's pickaxe was gone.

It may be possible that the auto-miner simply ejected it onto the ground and it despawned - I wasn't around to observe at the time - but even if that's the case, that would be very annoying behavior.  I would think if there is no place for the output, it should simply leave the pickaxe in the pickaxe slot as broken, and display some message like "Pickaxe currently broken".

**Comment by Vanhal** [comment]
It would have dropped it into the world, or into an adjacent container.

**Comment by sdaddy** [comment]
Tinkers' Tools don't despawn.

**Comment by mellamokb** [comment]
It appears they did get ejected onto the ground, and probably despawned.  They do despawn eventually, it just takes a lot longer, at least according to this: https://www.reddit.com/r/feedthebeast/comments/2c8bv6/do_tinkers_construct_tools_not_despawn/
