### ISSUE TITLE
PA Wrench 'pickup' crashing server

### ISSUE THREAD

**Issue by raum266** [Vanhal/ProgressiveAutomation#202]
When attempting to pick up a machine (specifically crafter, both Diamond and Iron, - unsure if it does it with others) with a PA Wrench, the server crashes using PA  v1.6.31 (1.7.10)

http://pastebin.com/KMpUfwKP

**Comment by Vanhal** [comment]
Oh! What are the other mods you're using that are using RF?

**Comment by raum266** [comment]
Off the top of my head (unable to log on and get a complete list until this afternoon)  were using Build craft and forestry that both use RF.  We're also using 'Power converters' which... Well, converts power into different forms for different mods.  I don't think Ic2 or Rail craft use Rf but could be mistaken.

**Comment by Vanhal** [comment]
Basically something is loading before PA that includes an incomplete version of the cofh lib. Should be fixable if you include cofh core or find out which other mod is including the lib.
