### ISSUE TITLE
AutoCrafter not working on 1.8.9 (Mods: Progressive Automation+Caterpillar)

### ISSUE THREAD

**Issue by Judgement2012** [Vanhal/ProgressiveAutomation#204]
It's exactly as the title says: The crafter refuses to work even when upgraded. The input recipe is provided, the basic materials are provided and the output slot is empty, but it still refuses to work. Any suggestions as to how to solve this problem?

**Comment by Vanhal** [comment]
Version? Can you post a screenshot?
