### ISSUE TITLE
screen is blanked when holding items

### ISSUE THREAD

**Issue by winsrp** [Vanhal/ProgressiveAutomation#207]
When using optifine, and activating shaders (including internal shader with no effects) if you hold an item in your hand (any item, from vanilla or any mod) the screen goes blank, having an empty slot selected shows the screen objects again.

Only happens when your mod is installed, if removed everything is back to normal.

MC 1.8.9,  forge for 1.8.9, with latest optifine.

Computer specs, nvidia 970gtx intel 4770k, 16gb ram.

If you need further details let me know.

**Comment by Vanhal** [comment]
This might be fixed.

**Comment by winsrp** [comment]
this is fixed except for the wrench, when holding the wrench screen is blanked.
