### ISSUE TITLE
Farmer stays in waiting status after a couple hours, plus some suggestions

### ISSUE THREAD

**Issue by winsrp** [Vanhal/ProgressiveAutomation#208]
Hi, 

Using the farmer to plant crops stays in waiting status without harvesting the crops after a couple hours. This is using normal minecraft seeds, in the config I have it that each upgrade raises the level by 3, and this is using a stone farmer, the crops are ready to gateher the machine has charcoal and an the proper tool inside, but it sits in waiting status without doing nothing, but it does burns fuel???

If I break it a put it again then it works and does all the work for a while, and then it sits back in this state.

On the suggestions part:

How about to add a place on the generator to fill your RF engine?
Make the wrench break the block with all its config when shift+normal click instead of right click.
Make a crops machine upgrade that makes it accept bonemeal, same for the chopper.

An upgrade for the miner, that lets me fill with dirt instead of cobblestone, or, just ignore dirt while gathering, or it could be a series of upgrades, like, ignore dirt, ignore stone, ignore... some other stuff, maybe even a new machine that allows me to make filters... for expample, put a base filter recipe, then combine that with some gold and a block of the thing you want to filter for example, dirt, and this will give you a dirt filter. Maybe even easier, make the wood machine be able to filter only one type of item, so you can modify the guy to add 1 filter slot, and you put there a block of the thing you want to filter, for example, a dirt block, then on the stone miner you have 2 spaces for filter, you can put, dirt and ... sand, for the iron 3 spaces, and so on... or something like that. 

I like the idea of having filter upgrades more than fixed filter spaces, so it can tailor it to any need I have, but one thing that would be nice is if you could actually see those filter placed in the GUI, instead of just throwing them in the magic upgrade space and have then banish. Like a space for normal upgrade cards, then one for the special cobble generator, and then you could have the filter spaces, so you could have like 5 or 6 fit in the GUI, same for the animal breeder, and the killer, so you could just see the cards there and take then away if you need to change the machine without having to destroy it to place it again.

Thanks

**Comment by Vanhal** [comment]
Is the machine chunk loaded for all that time yeah? Are all the spots that it harvests also loaded?
Can you give me an idea of the setup?

**Comment by winsrp** [comment]
Sure, let see if I can explain myself.

The setup is really simple:

I have 4 sections growing normal seeds, each section is a 3x3 block, with water in the middle, and the machine under the middle water block, all 4 sections are one next to the other, doing a 6x6 block, and that 6x6 is surrounded by 1 line of cobblestone. so it ends up in a 7x7, with the outer layer being cobblestone.

Now, since the upgrades level the machine by 3, after 3 upgrades, the range goes to 10, and each machine takes its own 3x3 group and overlaps 1 block of another group.

The chunks have been loaded all the time since I was doing construction, in my house with the resources gathered by the miner, chopper, breeder and killer, but the farmer is the only one that stops, after a couple runs, and actually some of the 4 farmes never even gathered anything, they were always in waiting status and consuming fuel.

Hope this helps. If you need more info let me know.
