### ISSUE TITLE
Support charging of Tinkers Construct tools with flux modifier

### ISSUE THREAD

**Issue by TheDallenger** [Vanhal/ProgressiveAutomation#213]
I't would be nice if PA machines would charge "flux tools" from tinkers construct (+Thermal Expansion 4), when supplied with RF energy. Just like the RF engine is.

Charging could be made automatic, but the tools are used until worn out. And then they require manual repair.

I can't find any other way to "automate" repair repair of the tools without requiring additional mods.

But maybe it would be too powerful?

**Comment by Vanhal** [comment]
Yeap, already asked, I've already said that would make it too powerful

**Comment by TheDallenger** [comment]
Wow, quick response :-)
I trawled the issue list before posting, but maybe I've should have put on my glasses.

Maybe you could eject the tools when they run out of RF, so they don't end up broken?
I realize that it probably will require special handling of the tools with flux modifier.
