### ISSUE TITLE
1.9, Forge 1802: Wrench cannot pick up items, changing output using it does nothing, lava bucket not working properly with generator

### ISSUE THREAD

**Issue by LordHellscream** [Vanhal/ProgressiveAutomation#225]
1. sneak using any blocks (generator, choppers) with the PA wrench doesn't pick up items
2. Can use set output function, but items still only come out from the top (for example the chopper: items only come out from the top even if i set north side as output, and query shows north is output).

3. Generator: empty bucket gets ejected (to the world, instead of container), using a hopper from the bottom for example will suck the lava bucket out (before it is used), but it won't get the empty bucket when its actually getting used. making it tedious to fuel the generator using lava bucket.

**Comment by Vanhal** [comment]
1) Yeap, it's to do with forge. Function isn't been called on the server side., waiting on forge fix.
2) Ah interesting. Didn't test that. Will check that out.
3) Probably same as 2.

**Comment by LordHellscream** [comment]
Just want to add: awesome mod! Very balanced (pretty hefty requirement on the resources, energy usage etc, making it feel real), simple to use (not overly complex like the other tech mod) and really improves the quality of life.

**Comment by jriwanek** [comment]
Any news on PA Wrench Rotation/Side configuration yet?

**Comment by Vanhal** [comment]
Should work in 1.6.46
