### ISSUE TITLE
Feature request: add basic conduits making this standalone

### ISSUE THREAD

**Issue by LordHellscream** [Vanhal/ProgressiveAutomation#226]
Is it possible to add simple conduits for RF and items making this fully functional standalone. playing on 1.9, very few mods work or have to download complex mods with pipes and conduits require custom materials unavailable to existing worlds.

**Comment by Vanhal** [comment]
I actually built another mod called Zoooooom that does exactly that!
It's converted to 1.9 but I'm waiting on something that's not in forge to do with actually display the pipes before I can release it.

**Comment by LordHellscream** [comment]
Awesome!

**Comment by Vanhal** [comment]
It is avail for 1.8.9 but i assume you're looking for 1.9

**Comment by Squaredude** [comment]
Also looking for the 1.9 version of Zoom. I was wondering if you have an ETA of its release. I'm really liking the PA mod, but since I've never used any RF mods and most haven't been updated for 1.9, I have no way of using the RF things in PA.

**Comment by jriwanek** [comment]
@Squaredude Take a look at Flux Ducts by FyberOptic for Ducts in the meantime, Also take a look at Electric Advantage by DrCyano, It's main power system is Electricity, but it's underlying lib (Power.Advantage) contains a block you can use to convert between Electricity and RF (Also others)

**Comment by Squaredude** [comment]
@jriwanek Thanks a lot! It seems like Flux Ducts is specifically for PA. I have no idea why I didn't find it before, as I generally look for mods in CurseForge.

For future reference: http://minecraft.curseforge.com/projects/flux-ducts
