### ISSUE TITLE
Request: (1.9)Buffer the "ticks" left from a fuel if RF meter is full, Auto-repair with mending enchant when hit blocks that gives xp orbs

### ISSUE THREAD

**Issue by LordHellscream** [Vanhal/ProgressiveAutomation#227]
if this is not the best place to place request please let me know, forum perhaps? :)

1. When using planter for example, energy don't get used continuously, so if filling it with a bucket of lava or a block of coal it will waste majority of the ticks for nothing once the generator is filled.  Is it possible to add a internal buffer for the fuel/ticks to the generator so they are saved when RF storage is full?

2. Is it possible to auto repair the durability on the tool if its enchanted with mending when hitting a block (coal ore, etc), since its already part of the game anyway. (right now i just need to grab the tool and go kill some stuff to repair it manually after a while). 

Question: I am assuming Fortune and Silk touch work already in addition to efficiency and unbreaking?

**Comment by Vanhal** [comment]
1. The wastage is part of the mod, use sticks or something with less burn time for less wastage.
2. Mending requires xp orbs to repair the tool. I suppose the machines could pick up xp orbs, but I'm not sure how you would use this in theory.

Fortune and silk touch should already work yes.

**Comment by 7eggert** [comment]
There was a mod called LiquidXP. I could never use it (it's 1.7 only), but it promised to collect XP as a liquid. You'd have one item pipe for new items, one for the harvest, one power cord for RF and a liquids pipe for XP.
