### ISSUE TITLE
progressive-automation-1.9-1.6.36 crashing dedicated forge server 1.9 build 1811 on startup with biomes-oplenty-1.9-4.0.0.1970 installed

### ISSUE THREAD

**Issue by kreezxil** [Vanhal/ProgressiveAutomation#230]
Issue: progressive-automation-1.9-1.6.36 crashing dedicated forge server 1.9 build 1811 on startup with biomes-oplenty-1.9-4.0.0.1970 installed

crash report:
https://gist.github.com/fd57d569a8a8495204c1

fml server latest:
https://gist.github.com/cb4638cf4db4d3e328fd

**Comment by kreezxil** [comment]
Update! I disabled biomes oplenty and it still crashes the server.


Issue: still crashes the server even without biomes oplenty

crash report:
https://gist.github.com/76651f56cb9fadc22768

fml server latest:
https://gist.github.com/b1e38ddcf89ccdb3ed1c

**Comment by tiarnia** [comment]
dont worry i get teh same thing just starting a single player world

**Comment by LordHellscream** [comment]
Same thing happened here single player. Same forge version.

**Comment by ArMoReDfUrY** [comment]
@kreezxil  reading your mod list... so many of those versions are broken with the new Forge.
I've been working through a similar list... been 4 days cutting out mods and testing alphas... still not got a clean boot yet XD list is getting thin now chin up

**Comment by kreezxil** [comment]
Look at my version 2.0.0 mod list available on Technic and at my website at http://kreezcraft.com. I've got a real same build going. My only issue is that the server environment is dragging and the mobs are leaving an odd trail. However in the client the world is lickety split fast and their after no mob trail artifacts.

I also realize this thread has nothing to do more with the current bug reports.

-----Original Message-----

**Comment by Vanhal** [comment]
This should be fixed right?
