### ISSUE TITLE
Chopper filling with tools

### ISSUE THREAD

**Issue by Pironemu** [Vanhal/ProgressiveAutomation#232]
Hello, Im having issues making choppers work properly on horizons daybreaker 1.7.10, when using either mekanisim or extra utilities pipes to push stone axes into the chopper they proceed to fill all of its inventory slots. From what I've read you had this issue before and fixed it, is there anything I could do to make it work properly? I've already set the side to input, could you maybe add a tool input only option to fix this?

**Comment by Vanhal** [comment]
What version?

**Comment by Pironemu** [comment]
Daybreaker 1.2.0  PA 1.7.10-1.6.21
