### ISSUE TITLE
[1.9]Server crashes when placing a wooden generator

### ISSUE THREAD

**Issue by kwpugh** [Vanhal/ProgressiveAutomation#233]
Crash report: http://pastebin.com/raw/X9Thj0DG

Forge: 1817
Mod: ProgressiveAutomation-1.9-1.6.38.jar

**Comment by matt81093** [comment]
The issue seems to happen whenever either a wooden or stone generator is used. I haven't had the issue happen yet with an iron or diamond gen. It seems to happen after using fuel in the generators, at least for me and one other.

Forge: 1811 for me
Mod version, same as kwpugh.  Although in a pack with other mods.
Crash Log: https://paste.ee/p/jjwnW

**Comment by matt81093** [comment]
I made a few changes to TileGenerator.java and got the game working again when using these generators.

Adding: `import net.minecraft.block.state.IBlockState;` and `IBlockState fireState = worldObj.getBlockState(firePos);`
Changing: `if ( ((fireBlock.isAir(null, worldObj, firePos))`
to `if ( ((fireBlock.isAir(fireState, worldObj, firePos))`

I'm not sure if the wood and stone generators still have a risk of producing fire or not, but that's somewhat of a different issue to the game crashing immediately upon use of the generators. Hope I could be of help, cheers.

**Comment by StarkRG** [comment]
I just had this happen when I placed an iron miner. I had moved it around before but this was the first time I placed it directly under an existing torch (attached to a wall). I had, at one point, placed it in a 1x1x1 notch in the wall and it was fine, but this time it crashed with the torch there.

**Comment by matt81093** [comment]
Was it the same crash? Did you get a crash log? @StarkRG

**Comment by StarkRG** [comment]
I've gone back over it again and I think is the same cause (stone generator kicking in), but it just seemed like it was related to the miner. Both times it's happened wee essentially simultaneous with me doing something with the miner (might have even been the same tick). The miner wasn't connected in any way with the generator so I think it was just coincidence.

**Comment by matt81093** [comment]
It seems like it. The stone and wood gen code are currently causing crashes. Hmm, I'll revert my code changes and test out the miner without my changes, but it could just be unlikely coincidence. Testing the miner itself and I haven't gotten any crashes.

**Comment by Vanhal** [comment]
Fixed this issue
