### ISSUE TITLE
1.6 on 1.8.9 TiC-Tools don't accepted

### ISSUE THREAD

**Issue by cyberpunkbln** [Vanhal/ProgressiveAutomation#234]
Hello,

on MC 1.8.9 no TiC-Tools will be accepted. Is this a bug or an upcoming feature?

thx
Kai

**Comment by Vanhal** [comment]
Yeah TiC wasn't out for 1.8 when I originally ported it. Will look at getting it compatible soon

**Comment by cyberpunkbln** [comment]
Thx

**Comment by Vanhal** [comment]
TiC tool support re-added

**Comment by cyberpunkbln** [comment]
thx4thework
