### ISSUE TITLE
1.9 Crash When using RF engine with nothing attached.

### ISSUE THREAD

**Issue by Thenosis** [Vanhal/ProgressiveAutomation#235]
I had the RF Engine sitting by itself off to the side to charge for when I got read to add another automated engine to it. This has caused the game to crash. 

Here is the crash report: http://pastebin.com/fFHpVknV

**Comment by matt81093** [comment]
Same as: https://github.com/Vanhal/ProgressiveAutomation/issues/233

@Thenosis Wood and Stone gens currently cause the game to crash.

Out of curiosity, what engine was being used?

**Comment by Thenosis** [comment]
@matt81093 I was using a Stone gen at the time. I had immediately upgraded to stone and skipped wood but didn't have enough to go to an Iron Gen yet.

**Comment by matt81093** [comment]
Fair enough, Iron and Diamonds gens work fine, but because of the chance for fire code.. the stone and wood gens crash. Until it's patched at least :P

**Comment by Vanhal** [comment]
Is fixed in next version
