### ISSUE TITLE
1.9 Planter Harvest issue

### ISSUE THREAD

**Issue by DeathProj** [Vanhal/ProgressiveAutomation#236]
http://pastebin.com/D46NsAmD

Forge version used: 1.9-forge1.9-12.16.0.1863-1.9

We used the More Foods with the planter as well and we used normal seeds from Minecraft with the planter..

**Comment by matt81093** [comment]
How did you produce the crash? @DeathProj

**Comment by DeathProj** [comment]
@matt81093 We just used some seeds from the More Foods mod with some normal seeds from Vanilla Minecraft.

**Comment by matt81093** [comment]
@DeathProj Which versions of the mods were being used? And.. were any other mods other than More Foods and Progressive Automation installed? Sorry for the late question, I had computer issues that had to be dealt with.

**Comment by DeathProj** [comment]
More Foods version: More Food 1.15b 1.9 from Curse
Progressive Automation version: ProgressiveAutomation-1.9-1.6.38.jar from Curse

There was way more mods than this two but I don't think that it does matter because as it can be seen on the crash-report only Progressive Automation started the crash. But if I'm wrong and it does matter then I'm gonna share the modlist.

**Comment by Vanhal** [comment]
Issue seems to be with More Food. I'm getting Null pointer errors when trying to access any field of itemstack with any of the more food items. Can't find the source of More food so can't check it out for sure.

**Comment by matt81093** [comment]
@DeathProj @Vanhal 
A bug report could be filed here:
https://bitbucket.org/JoseTheCrafter/food-plus/issues?status=new&status=open
I just remembered this problem and decided to look around.
