### ISSUE TITLE
Chopper ejection

### ISSUE THREAD

**Issue by Alzarath** [Vanhal/ProgressiveAutomation#239]
For such a vanilla-friendly mod, the Chopper doesn't work too well with the most basic of all trees. The Chopper ejects *above* it. Placing a chest above it makes it so Oak trees won't grow. It's very counter-intuitive.

I'd suggest you either make the Chopper placed in-ground so trees can still grow around it and allow you to put a chest on top or make the Chopper eject to adjacent inventories, not just above.

**Comment by Vanhal** [comment]
You can use the wrench to make some other other sides eject instead, or put a hopper under it.
