### ISSUE TITLE
Chopper doesn't support non-vanilla trees

### ISSUE THREAD

**Issue by iTayGNR** [Vanhal/ProgressiveAutomation#242]
Just tried to use the chopper with the Ebony wood (from Biomes O' Plenty). Unfortunally, The Chopper doesn't support any of BoP's Trees.

I'd like to know if that's a bug or is it supposed to be like that..

**Comment by Vanhal** [comment]
Version? cause I know it works in 1.7

**Comment by iTayGNR** [comment]
1.9

**Comment by iTayGNR** [comment]
forge-12.16.0.1865 if this helps

**Comment by iTayGNR** [comment]
anything?

**Comment by pikeminnow** [comment]
BOP Trees still do not work with PA
forge 1.9-12.16.1.1887
PA 1.6.42

**Comment by ab9rf** [comment]
BOP Trees still do not work with PA in 1.9.4-1.6.47 (Forge 12.17.0.1976, Biomes-O-Plenty 1.9.4-4.1.0.2033).

**Comment by ab9rf** [comment]
It appears that BOP saplings are not instances of IPlantable, and thus the test that the sapling must be an instance of IPlantable fails (TileChopper.java @ L408). This is probably a Biomes-o-Plenty bug; the Forge documentation on IPlantable strongly suggests that saplings should support IPlantable. Pinging @Glitchfiend for comment.

**Comment by aadeknor** [comment]
I have the same issue and also with forestry saplings.
Modpack: All The Mods 1.10.2 v1.5
PA 1.10.2-1.6.49
BOP 1.9.4-4.1.0.2052
Forestry 1.10.2-5.2.1.204
Forge 12.18.1.2018

**Comment by ab9rf** [comment]
BOP saplings now work with the most recent BOP release, due to BOP making its saplings implement IPlantable.
