### ISSUE TITLE
PA right-click not working

### ISSUE THREAD

**Issue by vladp995** [Vanhal/ProgressiveAutomation#244]
sneak right clicking seems to pick up machines and change mods properly, but right clicking the machine side just opens the machine interface and does not post anything into the chat nor actually change that side mode

I'm using PA at version 1.6.45 as part of the Arisen 2 modpack for minecraft 1.9.4

**Comment by vladp995** [comment]
Tried it now on 1.9.4 with forge 12.17.0.1909 and ProgressiveAutomation-1.9.4-1.6.45.jar
same, right click opens interface but does not change the mode

**Comment by Vanhal** [comment]
This was fixed with 1.6.46
