### ISSUE TITLE
pa wrench not working 1.9.4

### ISSUE THREAD

**Issue by wackoamd1** [Vanhal/ProgressiveAutomation#245]
when i select the pa wrench i keep the previous item in my hand and i cant move . 
well by cant move i mean that my screen stays where it is facing but i get a weird ghostlike image of the surrounding im looking at and that moves when i move my mouse.

mc 1.9.4 forge 1.9.4 12.17.0.1910

**Comment by Vanhal** [comment]
PA version?

**Comment by wackoamd1** [comment]
ive alrdy found the error , it doesnt play nice with optifine , disabled optifine and now its working
