### ISSUE TITLE
[1.7.10] Crash when harvesting Thaumcraft trees

### ISSUE THREAD

**Issue by b0bst3r** [Vanhal/ProgressiveAutomation#246]
Not sure if you're still developing 1.7.10, in case you are have this :) 

http://pastebin.com/nh4KThxL

Reading into the crash it happened in SSP when the chopper tried to break Thaumcraft tree leaf blocks.

I've asked roffa91 for that information for you when he reported it here
https://github.com/BevoTechPack/BevoTechPack/issues/987

Forge 1566
Progressive Automation 1.6.34 
Thaumcraft 4.2.3.5

**Comment by Vanhal** [comment]
That issue again. I think it was fixed in 1.6.35... But if its not let me know and I'll see what I can do.

**Comment by b0bst3r** [comment]
Oh sorry my bad I missed the update.
