### ISSUE TITLE
1.9.4-1.6.46 stone tier not active in JEI

### ISSUE THREAD

**Issue by kreezxil** [Vanhal/ProgressiveAutomation#247]
It is craftable, however in the JEI, it doesn't show up with a "+" that allows injection to a table, the wooden miner does however.

**Comment by kreezxil** [comment]
So I guess this a JEI integration issue.

**Comment by Vanhal** [comment]
![2016-05-31_09 25 33](https://cloud.githubusercontent.com/assets/7526890/15668155/b9893c88-2711-11e6-8f10-bcaa47a0e8e2.png)

Seems to work for me....
