### ISSUE TITLE
Reference to Inventory Sorter mod (by cpw) dupe issue

### ISSUE THREAD

**Issue by RaineAndrews** [Vanhal/ProgressiveAutomation#250]
https://github.com/cpw/inventorysorter/issues/19

**Comment by cpw** [comment]
Update to latest inventory sorter - PA is not using monolithic inventories, so the different slot types are all jumbled together. Fix is that inv sorter just ignores hybrid inventories, so sorting won't work anymore.

**Comment by RaineAndrews** [comment]
And PA should use monolithic inventories?

**Comment by Vanhal** [comment]
What are monolithic inventories out of curiosity?
