### ISSUE TITLE
1.9 Wither Diamond - to Nether Star dupe Via Uncrafting Grinder

### ISSUE THREAD

**Issue by koalalord9999** [Vanhal/ProgressiveAutomation#251]
Soo... I was messing around uncrafting things in this grinder, and I made the mistake of uncrafting a diamond axe (any diamond tool works except pickaxe in this modpack -- Arisen) When you uncraft the axe, it uses the first recipe which is the one with the wither diamonds. You can then uncraft the wither diamonds to make nether stars, and get your diamonds back so you can keep making them. This video shows what was happening.
https://youtu.be/jP8gXFoFevE
LothrazarMinecraftMods/UncraftingTable#3

This issue could be fixed by making the wither diamond recipe not show up before the vanilla recipe :)

**Comment by Vanhal** [comment]
This isn't an issue with this mod I'm afraid!

**Comment by koalalord9999** [comment]
It may not be, but the way minecraft loads the recipes, it seems to think that the wither diamond tools are the default recipe for diamond tools xD

**Comment by Vanhal** [comment]
FIFO I assume, I not sure of how I would even go about select the order they get put in.
