### ISSUE TITLE
Too much expensive...

### ISSUE THREAD

**Issue by aviallon** [Vanhal/ProgressiveAutomation#252]
In order to automatize the harvesting of 2 trees at a distance of _3 blocks_, you need **_1614_** iron ingots, which is way too much expensive. I think it's a bug. For information, i'm running this mod on MC 1.9.4 with Forge 12.17.0.1936

**Comment by Vanhal** [comment]
Option in configs to increase the range  of each upgrade. Not a bug.

**Comment by aviallon** [comment]
but, I think you should increase the default values, no ? Just a suggestion

**Comment by Vanhal** [comment]
Nope, never

**Comment by 7eggert** [comment]
You should have a 5x5 matrix of trees and use a stone chopper with range 24 for good results. If you automatize tool supply and energy, you'll lose 2 of those possible trees, but it runs well. I have 4 of those farms for my energy supply and I need to get rid of extra wood.

For bigger farms you'll need faster tools, but unless your golem farm runs in overdrive, it's not worth it.

For your two-tree setup, you should use two wooden choppers or stone choppers with range 1, depending on the type of axe you want to use.

**Comment by aviallon** [comment]
Thank you guy ! I changed a little bit the config because I'm using this mod with Botania, and now it runs very well. I just need a couple of iron upgrades to harvest my 4 trees.
