### ISSUE TITLE
Killer does not work with 1.9 battle swing cool down.

### ISSUE THREAD

**Issue by desagas** [Vanhal/ProgressiveAutomation#254]
The killer does not work as intended in 1.9. The killer does not take into account the cool down of sword swings that came with the 1.9 battle update. So, as a result, even a sword with 60 attack and 10 speed will only do .5 damage to any mob, regardless of its armour or type.

Is there a fix for this, or a way around it?

Also, your in breaking tools that are crafted from the wither iron now take damage, and quite quickly, in the killer.

Do not ask for a crash report, as there was no crash.

If you want to recreate the issue, I am playing 1.9.4 Arisen 2, located on the curse launcher.

Thank you.

**Comment by desagas** [comment]
I was using both a nether advanced nether sword with 60 attack. I also tried a swipe diamond sword for super high attack speed. Both only cause .5 heart damage each hit.

**Comment by thepaperpilot** [comment]
> Also, your in breaking tools that are crafted from the wither iron now take damage, and quite quickly, in the killer.

That's a separate issue, and probably related to #260.

**Comment by thepaperpilot** [comment]
Before fixing I think we should determine something about what the desired behavior should be. I suggest the killer always do a full swing, because if it's actually the length of time between hits then a diamond killer may seem detrimental. Of course, with weapons that are balanced around being slow, this might seem problematic.

**Comment by thepaperpilot** [comment]
Actually, I just looked and it seems this issue was resolved in #241. Should we close this?
