### ISSUE TITLE
[1.10.2] Stone Chopper Crashing Server

### ISSUE THREAD

**Issue by Stuart74** [Vanhal/ProgressiveAutomation#263]
The stone crusher crashed the server and the server continually crashed on startup had to rollback the region affected and remove the stone chopper.

Progressive Automation Version: 1.10.2-1.6.48
Forge Version: 12.18.1.2014

Crash Report :
[crashreport.txt](https://github.com/Vanhal/ProgressiveAutomation/files/373993/crashreport.txt)

**Comment by Stuart74** [comment]
Just curious if there is still any support on this mod?? Seems its been dormant for some time no real commits to it for 2 months as far as what it says on github. If this  mod is nolonger supported or being updated i rather know now and remove the mod from the pack.

**Comment by Vanhal** [comment]
There is, I just work

**Comment by Vanhal** [comment]
What type of saplings are you using?

**Comment by Stuart74** [comment]
Normal oak saplings

**Comment by Vanhal** [comment]
Right, I've pushed up a new version now that "may" fix the issue.... Let me know.

**Comment by Stuart74** [comment]
No probs i will be pushing the updates tomorrow to curse for my modpack so should know within the next day thanks for the help

**Comment by Stuart74** [comment]
Seems to be fixed  now thanks for the help great mod
