### ISSUE TITLE
Suggestion: TESLA Support

### ISSUE THREAD

**Issue by jburrows82** [Vanhal/ProgressiveAutomation#264]
Many mods are jumping on-board the Tesla train and adding support for this new energy system. There are advantages of using the new energy api as a developer, and as a player. Please check it out, if you haven't already, and at least consider it.

[Curse](http://minecraft.curseforge.com/projects/tesla?gameCategorySlug=mc-mods&projectID=244651)    & [Github](http://github.com/Darkhax-Minecraft/Tesla) links

Thank you!

**Comment by Vanhal** [comment]
Considered it. Don't want to thanks.
