### ISSUE TITLE
Able to Push Items in/out of Farms

### ISSUE THREAD

**Issue by MDR-DEV-GIT** [Vanhal/ProgressiveAutomation#274]
I've currently only tested with trying to pump wheat into an Animal farm using EnderIO Item conduits. 

Placed a chest near by, 
connected the chest to the Diamond Animal Farm via EnderIO Item Conduits. 
Verified the connector connected to the Chest was in Extract mode. 
Switched the end connected to the Animal Farm to Insert. 
Put wheat into the chest 
Checked Animal Farm (Still Empty/not filling with Wheat) :(

**Comment by Vanhal** [comment]
Did you wrench the side of the animal farm that you're pulling from with the PA wrench?

**Comment by MDR-DEV-GIT** [comment]
Hi Vanhal, thanks for the response. 
![2016-09-01_09 53 42](https://cloud.githubusercontent.com/assets/2915502/18172293/758d96de-702a-11e6-8a1a-b273dd01643d.png)


I'm not trying to pull from, I'm trying to push wheat to. 

"down side set to: Input"

Not sure if it's relevant to the situation but I have an Ender IO Electrical Conduit and an Ender IO Item Conduit both going into the bottom (because Ender IO supports both occupying the same block). See attached screenshot.

![2016-09-01_09 53 42](https://cloud.githubusercontent.com/assets/2915502/18172293/758d96de-702a-11e6-8a1a-b273dd01643d.png)

**Comment by MDR-DEV-GIT** [comment]
Please disregard. This was due to confusion on my side. I was not familiar with the fact that EnderIO's default Extract behavior for the Item Conduit was set to Active with Redstone signal.

Thanks and sorry!
