### ISSUE TITLE
RFEngine doens't found.

### ISSUE THREAD

**Issue by fnsch** [Vanhal/ProgressiveAutomation#276]
Hello,

I'm having some issues, RFEngine and Generator are missing. I tried to craft them, and nothing happend, I tried search in criative mode and they are not there, I tried even via the comand line /get. Do you have any ideia about this?

Thanks, this mod is incredible.

**Comment by Gunner76th** [comment]
What version of PA are you using, and what Minecraft version? I am running MC 1.10.2 and PA version 1.6.51 and both the Generators and the RF Engine are listed and craftable. In my server, RF Engine is block ID 9177 progressiveautomarion:RFEngine, and the generators are block id 9196, 9197, 9198, and 9199 progressiveautomation:Generator progressiveautomation:GeneratorStone progressiveautomation:GeneratorIron progressiveautomation:GeneratorDiamond

Also, as a reminder the correct command to cheat things in from the console is /give <player> <item> [amount] [data] [dataTag]

As an example, say you want to give player Jimmy 16 chiseled sandstone. On the console you would enter the following: /give Jimmy minecraft:sandstone 16 2

**When doing a give command where you need to enter dataTag information, you must put it inside curly brackets { } such as with the enchantment book Efficiency V: /give Jimmy minecraft:enchanted_book 1 0 {StoredEnchantments:[0:{lvl:5s,id:32s}]}

**Comment by Vanhal** [comment]
I am unable to re-produce this. The only reason they would not be showing is if RF support was disabled in the configs.
