### ISSUE TITLE
Crash when right-clicking a machine with the PA Wrench

### ISSUE THREAD

**Issue by QuantumSheep** [Vanhal/ProgressiveAutomation#279]
Crash when right-clicking a machine with the PA Wrench:

http://pastebin.com/Yfrc4MVG

Mod version: 1.10.2-1.6.51
Forge version: 1.10.2-12.18.1.2092

**Comment by DnTheMn** [comment]
can also confirm same thing happening here too https://github.com/whatthedrunk/allthemods/issues/228

**Comment by Vanhal** [comment]
Should be fixed in 1.10.2-1.6.52
