### ISSUE TITLE
[1.7.10] Crash used with Mekanism Cables

### ISSUE THREAD

**Issue by Master-Jynx** [Vanhal/ProgressiveAutomation#280]
Mekanism 281
Progressive Automation 1.6.34
Forge 1614
plus 181 other mods on an SMP Server

When PA's Chopper is fed from a side that it can actively plant from, the game will crash when
you first enter that region, or if you are in that area when you logon.

If you place chopper with a Basic Cable connected to the front side and leave the game,
no crash will occur if you rejoin quickly.
A crash will occur if you restart the client and rejoin.
The Server and the client will both crash.
The clients error message is about bad packets when trying to connect, I don't believe it relates.
The server error message we get is at
http://pastebin.com/fjFvM9h4
and , No, its not Thaumcraft related, the crash is on an island with 1 oak tree more then 40 blocks away
and 4 slime trees more then 30 away.

The crash only seems to happen when pipes from another mod are connected to a side that it has
been upgraded enough that it will plant on that side.

Shouldn't the chopper be used the same way a planter is?
the planter plants 2 blocks above it allowing the center block to be planted on or used as a water source.
If the chopper were the same, then this crash wouldn't happen, and you could use more sides then just the bottom for power insertion and extraction, which only EIO conduits can do from the same block.

**Comment by Vanhal** [comment]
Can you retest with 1.6.35 please.

**Comment by Master-Jynx** [comment]
They only update at the beginning of the month, to reduce their workload, and to reduce player complaints.
But i did test it in SSP, with the same modpack and 1.6.34 does crash, while 1.6.35 does not crash
under the same conditions.
I'll respond again, after they update, if the crash does occur on SMP.
