### ISSUE TITLE
Feature suggestion: population thresholds for killing and breeding

### ISSUE THREAD

**Issue by mmehnert** [Vanhal/ProgressiveAutomation#283]
Although it is possible to achieve some sort of steady state where the killing equals out the breeding by clever positioning of the killer and limiting its radius, I often end up either killing all animals that I want to breed or breeding way to many.

It would be nice to have an option for the farmer to stop breeding when a certain population is reached within it's configured radius and for the killer to stop killing when the population of animals is below a certain number within a radius that should be freely configurable (in order to include the area of the farmer)

**Comment by Vanhal** [comment]
The idea is that you use vanilla methods (Like having the adult animal on top of fences) to separate out the animals you want to kill.

**Comment by mmehnert** [comment]
Could you explain that in more detail? I could not figure out a method to maintain a stable population and could not find any documented way to do so. :-(
