### ISSUE TITLE
Crash with Wreng ( 1.10.2)

### ISSUE THREAD

**Issue by Golgatron** [Vanhal/ProgressiveAutomation#284]
Hey client crashed with  PA Wrench shift right klick on Planter

**Comment by DnTheMn** [comment]
can confirm https://github.com/whatthedrunk/allthemods/issues/228

**Comment by Xalorous** [comment]
also confirm http://pastebin.com/04y63DZg

**Comment by Xalorous** [comment]
Duplicate of #279

**Comment by Caleb-Ardern** [comment]
Temporary fix config line 47 False
this should remove the use of the wrench

**Comment by kythorn** [comment]
@Caleb-Ardern unfortunately breaking it without the wrench causes all upgrades to be lost. Still mostly a showstopper for this mod I think.

**Comment by Vanhal** [comment]
Should be fixed in 1.10.2-1.6.52
