### ISSUE TITLE
1.10.2 Planter leaving dropped items on ground

### ISSUE THREAD

**Issue by Gunner76th** [Vanhal/ProgressiveAutomation#286]
I have a farm I am setting up to make biodiesel using sugarcane and hemp from Immersive Engineering. When the planter goes and harvests both the vanilla sugar cane or the hemp, about 25% or more of what it harvests remains on the ground as dropped items. The internal inventory is nowhere near full, in fact a vanilla hopper is enough to keep it empty so as to not cause a backlog. 

In previous versions, I do not recall this ever happening. With it leaving even vanilla sugarcane on the ground, this can potentially cause this machine to be unusable as it could cause excessive dropped items and affect TPS on the server.

**Comment by Vanhal** [comment]
Should be fixed in 1.10.2-1.6.52
