### ISSUE TITLE
Feature Request; 1.10 TiC support

### ISSUE THREAD

**Issue by Deshiba** [Vanhal/ProgressiveAutomation#288]
Currently the chopper and the miner do nothing with Tinkers' Constructs automsmelt, could this be added?

**Comment by Vanhal** [comment]
My thoughts are to not support autosmelt. I feel it would just break it too much. Totally free charcoal farm.... no....

**Comment by Deshiba** [comment]
Currently you can extract the wood and smelt it with woodplanks to get charcoal. It takes longer but in effect it's free charcoal regardless, the yield is just lower. 52 wood logs equals 45 coal taking 450 seconds to smelt vanilla style (other mods speed this up to about instant). Supporting autosmelt would increase the yield by ~15%,.

If time is the biggest cost constraint then the working speed of the chopper could be slowed down when using an autosmelt tool. This would also increase the coal cost to run the machine itself, lowering the yield in the proces.
