### ISSUE TITLE
Add Forge energy Support

### ISSUE THREAD

**Issue by Deshiba** [Vanhal/ProgressiveAutomation#289]
Currently the generator won't power AE2 machines. I tried setting the output, using it straing on machines, using a dense energy cell and using the energy acceptor. The generator just keeps storing power but doesn't share it with AE2.

**Comment by Vanhal** [comment]
So, from what I can see from the source code of AE2, it doesn't look like it's using RF any more in 1.10, I could be wrong about that though...

**Comment by Deshiba** [comment]
Seems to work fine via the energy acceptor using simply generators:
http://nl.tinypic.com/r/23lcuf6/9

**Comment by Vanhal** [comment]
Can you link me to simply generators, I can't seem to find it

**Comment by Deshiba** [comment]
Sorry, Simple Generators*. Pretty sure it works with enviromental tech too since it runs off ValkyrieLib, but I'd have to test that.

https://minecraft.curseforge.com/projects/simple-generators

**Comment by Deshiba** [comment]
After a couple of tests it is as I suspected. Enviornmental tech works as wel, but any of the other mods I tried like Immersive engineering, Draconic evolution, Railcraft and Deep Resonance do not work at all.

Pretty sure ValkyrieLib does something to force RF on AE

**Comment by Vanhal** [comment]
So after some further reading AE2 only supports tesla and forge energy at the moment. So I suspect that simple generators is outputting one of those instead/as well as RF.

While I have no plans to add tesla support, I do intend to add forge energy support, so once that's in it should work.

**Comment by Vanhal** [comment]
Completed for 1.7
