### ISSUE TITLE
Pusher Block

### ISSUE THREAD

**Issue by Vanhal** [Vanhal/ProgressiveAutomation#29]
Maybe have a pusher block to move the miner?

**Comment by Badcholo** [comment]
There are upgrades if you want to mine a bigger area out. No need for pushing the block with pistons and such. It would be nice to have a Horizontal miner that mines side ways instead of just down. since it's the best way to get diamonds and right now it kinda sucks for that.

**Comment by NoX-programer** [comment]
I am sure we don't need to invent the functional already invented. Take a look of mod Funky Locomotion (for example).

**Comment by Vanhal** [comment]
Agreed. It's very unlikely that I'll be adding this.
