### ISSUE TITLE
[1.10.2] Crash on start up

### ISSUE THREAD

**Issue by ParaMotor** [Vanhal/ProgressiveAutomation#290]
Minecraft crashes on loading.
http://pastebin.com/JyziYB9c

I'm using forge-12.18.2.2122 and Progressive Automation-1.10.2-1.6.52.

**Comment by Vanhal** [comment]
Interesting, do you have diamond tier disabled in the configs?

**Comment by ParaMotor** [comment]
Yes I did disable diamond tier.

**Comment by Vanhal** [comment]
Yeap, that would do it. Gonna push a fix in the next few hours for this!
