### ISSUE TITLE
Item transport troubles

### ISSUE THREAD

**Issue by Candyman711** [Vanhal/ProgressiveAutomation#293]
Cannot access chopper/crafter inventory for item extraction or insertion with item transfer nodes/pipes,Steve's factory manager.  

Forge:12.18.2.2125
Progressive Automation: 1.10.2-1.6.53

**Comment by winsrp** [comment]
I will second this one, and add also that it won't work with storage network pipes, rftools control, actual additions and enderio either, and tested on all the blocks, chopper, crafter, miner, farmer, etc etc... none of them work (and yes I have specified their fuel inputs and normal inputs/ouputs using wrench and still wont work.)

**Comment by Vanhal** [comment]
Implemented Inventory capabilities which should fix this (and other similar issues) in 1.7. (tested with extrautils)
