### ISSUE TITLE
[Bug] NullPointer after placing 

### ISSUE THREAD

**Issue by Techtronik** [Vanhal/ProgressiveAutomation#296]
It's not crashing but it just keeps throwing nullpointers when i place a progressive automation machine (any machine) and try to interact with anything else that has an interface. the only things i can access while the machine is placed is the player inventory and PA machine inventory and i need to leave and reload the world to get the items to show up in my inventory after i break the machine

Game Output:
http://pastebin.com/TASvYahX

**Comment by Techtronik** [comment]
also, this is in the Skyexchange modpack on the curse launcher

I'm putting the mod list into another paste, i'll edit this when i've finished

**Comment by Vanhal** [comment]
Duplicate of #298
