### ISSUE TITLE
Incompatibility with something in Sky Exchange Mod Pack.

### ISSUE THREAD

**Issue by VegettaPT** [Vanhal/ProgressiveAutomation#298]
Every time i open Chopper and exit i cannot open anything else (crafting table, chests, etc).. I've to re-enter the world to work again. 

I'm using Sky Exchange Mod (1.10.2) with Veinminer and FastLeafDecay-V11

**Comment by Inxistance** [comment]
I'm having the same issue as well. Once you open the GUI for the Chopper and then close, nothing else is accessible.

ProgressiveAutomation-1.10.2-1.6.53.jar

Using Skyexchange 1.2.4 as it was released. 

Thx!

**Comment by Squaredude** [comment]
Seems to be Sky Exchange, as I don't have that mod and all GUI blocks work as intended.

**Comment by sybershot** [comment]
Having the same problem, using Skyexchange 1.2.4. Here's some bit of error that might help.
http://pastebin.com/NcMA9xij
