### ISSUE TITLE
Killer doing only one point of damage(1/2 heart) instead of matching damage of the sword used.

### ISSUE THREAD

**Issue by Kenqr** [Vanhal/ProgressiveAutomation#301]
Tested on Minecraft 1.10.2 with only PA and TheOneProbe installed.

**Comment by 7934345** [comment]
Same situation, and found this thread.

needs help~

**Comment by Vanhal** [comment]
Was sure this was fixed :(

Will look into it again.

**Comment by 7934345** [comment]
any news ?
