### ISSUE TITLE
[1.10.2-1.6.53]Little or no difference in tiers

### ISSUE THREAD

**Issue by mainframecn** [Vanhal/ProgressiveAutomation#302]
I've ran a few test between the tiers and there seems to be little or no difference between the chopper tiers. 
The test was between a wooden chopper and diamond chopper, same amount of wood to cut down and same tool. ("equippable" tool modified in config) Machines running on RF.

**Comment by Vanhal** [comment]
You actually said it yourself. There is almost no difference except for the tools you use in the machine, the better tools are faster. So the only reason to use higher tiers is to use better tools. The exception here is (for the chopper) the leaves break faster in the better machines.

**Comment by mainframecn** [comment]
I see, I thought i read somewhere that the tool didn't have impact on the speed of the machine.
