### ISSUE TITLE
output not transferring to extra utils 2 transfer pipes (1.10.2)

### ISSUE THREAD

**Issue by SDUBZ** [Vanhal/ProgressiveAutomation#303]
forge-1.10.2-2209
progressive auto: ProgressiveAutomation-1.10.2-1.6.53

exu2: extrautils2-1.10.2-1.1.3d

was using chopper and noticed it wouldnt output to thew transfer node dont know if its your side or exu2's side

also to be noted it doest output to yabba barrels either

**Comment by Vanhal** [comment]
Yeah this is to do with #289
