### ISSUE TITLE
TiC autosmelting and unbreakable don't seem to work

### ISSUE THREAD

**Issue by red-mist** [Vanhal/ProgressiveAutomation#304]
Experimenting with the chopper in resonant rise 4; found unbreakable axe (5*reinforced) still breaks and autosmelting (TiC firewood) doesn't actually smelt the logs into charcoal as it does when using the axe manually.

**Comment by Vanhal** [comment]
Autosmelting will never work, i'd actually have to program it in myself.
I honestly don't know why the reinforced doesn't work, but honestly it would really make the balance too broken imo.
