### ISSUE TITLE
Server completely crashes upon using Iron Miner on Project Red basalt

### ISSUE THREAD

**Issue by dragonfree97** [Vanhal/ProgressiveAutomation#308]
Tried on singleplayer and multiplayer (MC 1.10.2 running Force 2185)

PA version: 1.7.0
PR version: 4.8.0.17

Server crashes when you place the iron miner down and set it running. Attached is the crash log
[crash-2017-02-15_19.41.59-server.txt](https://github.com/Vanhal/ProgressiveAutomation/files/778239/crash-2017-02-15_19.41.59-server.txt)

**Comment by Vanhal** [comment]
Works fine for me. From the error log it looks as if something is wrong with minetweaker.
