### ISSUE TITLE
1.11.2 Support

### ISSUE THREAD

**Issue by 7934345** [Vanhal/ProgressiveAutomation#310]
Im glad to have this mod on 1.11.2 server.

Thx, XD

**Comment by Vanhal** [comment]
thanks

**Comment by keithaw** [comment]
How does one get the 1.11 version?

**Comment by 7934345** [comment]
@Vanhal Please update the 1.11.2 file in https://minecraft.curseforge.com/projects/progressive-automation-early-miner/files

XD

**Comment by Squaredude** [comment]
Can we get an ETA for 1.11.2? Is there anything we can do to help with a version bump?
