### ISSUE TITLE
Request a feature

### ISSUE THREAD

**Issue by buddy3315** [Vanhal/ProgressiveAutomation#313]
What would be nice is a scanner that works the same way as the miner vertically and upgrades the same way. Runs on coal and rf (love that Idea btw). Also a non upgraded scanner only vaguely suggests an ore but not actually identifies what type or quantity. 
As you upgrade the range and the quality of the information is expanded

Also the miner in iron and above should have an upgrade to turn lava into obsidian when encountered.

I don't see anyone out there with this mod (I have searched and I believe it would fit just nicely with this mod)

**Comment by Psycho-Ray** [comment]
Put or high tier pickaxe. Check how many total block blocks there are to be mined. Now put an Wooden Pick Axe and check again. The difference is the amount of ores.

But think showing what are those ores is a bit broken.
