### ISSUE TITLE
[Crash][MC1.10.2- Mod v1.7.0] Crash when attempting to output power to ImmersiveEngineering wire connectors

### ISSUE THREAD

**Issue by ToadsworthLP** [Vanhal/ProgressiveAutomation#316]
If I build this contraption:
c
G
where c is a ImmEng wire connector and G is any ProgressiveAutomation generator, the game crashes as soons as it tries to output stored power to the connector.
Here's the log: https://paste.ee/p/nL5pl
It seems to have a problem in TileCapacitor.java in line 193, which is a simple check (https://github.com/Vanhal/ProgressiveAutomation/blob/master/src/main/java/com/vanhal/progressiveautomation/entities/generator/TileGenerator.java#L193). I couldn't fix this myself, but maybe you are able to :)

**Comment by Vanhal** [comment]
Fixed in 1.7.1
