### ISSUE TITLE
1.10 chopper fails to cut IC2 rubber trees (only on blocks that can have resen)

### ISSUE THREAD

**Issue by SwiftOne** [Vanhal/ProgressiveAutomation#318]
(as discovered in Forever Stranded modpack)  I have a stone chopper with a TCon paper hatchet.  It plants and chops IC2 rubber trees EXCEPT for the tree blocks that have the possibility of resin (doesn't seem to matter if resin is there or not, just that it can be).  

I manually verified that the hatchet can chop those blocks, FWIW.

**Comment by Vanhal** [comment]
Fixed in 1.7.1
