### ISSUE TITLE
Invalid Metadata for Oak Leaves with Chopper

### ISSUE THREAD

**Issue by scottosx** [Vanhal/ProgressiveAutomation#319]
Metadata set incorrectly to 8 which does not exist for oak leaves. Some leaves set correctly (maybe first 2?) others are not.

![2017-03-24_14 23 32](https://cloud.githubusercontent.com/assets/5866215/24310416/e0d296e2-109d-11e7-8073-e4294ebb2eee.png)

**Comment by Vanhal** [comment]
Fixed 1.7.1
