### ISSUE TITLE
Feature Request:  Moo Fluid Support

### ISSUE THREAD

**Issue by Jo-Mamma75** [Vanhal/ProgressiveAutomation#320]
Vanhal,
I am Jo_Mamma75, one of the pack developers for iskall85's FoolCraft played by iskall85, Xisuma, BDoubleO100, Rendog, GoodTimesWithScar, etc.  We had an issue with the Mechanical User from Extra Utilities 2 and had to disable it from the pack (was causing server crashes) and were looking for a 1.10.2 alternative for milking fluid cows from the Moo Fluids mod as well as something that would support AgriCraft.  Your Progressive Automation mod looks like the perfect candidate to be added to the pack but, unfortunately, it does not work with the Moo Fluid cows.  Would it be possible to add this feature to an updated version of the mod so we can include it in our pack?  I will also post this in the Github as a feature request but wanted to send the message here as well.
I/we sincerely appreciate you taking the time to consider our request and look forward to hearing back from you.
Thanks in advance.

Jo_Mamma75
iskall85 Pack Development Team
Modded Server Administrator

**Comment by Vanhal** [comment]
Yeap, should be added in 1.7.1 later today.

**Comment by Jo-Mamma75** [comment]
Small problem with the 1.7.1 update.  Added it to the pack for dev testing and got the following.

Forge Mod Loader has found a problem with your minecraft installation
You have mod sources that are duplicate within your system
Mod Id:  File name
examplemod:  ProgressiveAutomation-1.10.2-1.7.1.jar
examplemod:  Modifiable-Armor-2-1.10.2-2.0.2.jar

[http://imgur.com/JZvAA6W](http://imgur.com/JZvAA6W)

**Comment by Vanhal** [comment]
Fixed 1.7.2, re-upped

**Comment by Jo-Mamma75** [comment]
Thank you.  Finally got around to testing it this evening and everything looks great.
