### ISSUE TITLE
Mod ID Issue

### ISSUE THREAD

**Issue by Darkosto** [Vanhal/ProgressiveAutomation#321]
https://i.artdude.uk/darkosto/nghO6ZRo.png

MC: 1.10.2
Progressive Automation: 1.7.1

https://github.com/WhiskyTangoFawks/Expedition/issues/129

**Comment by Vanhal** [comment]
Yeap, I'm an idiot :(

**Comment by Vanhal** [comment]
Fixed 1.7.2, re-upped
