### ISSUE TITLE
Chopper has issue with IC2 Rubber Trees. 

### ISSUE THREAD

**Issue by alikhan0498** [Vanhal/ProgressiveAutomation#322]
Whenever the chopper tries to chop rubber trees from IC2 it ignores the logs with rubber resin on.

**Comment by Vanhal** [comment]
What version of PA are you running?

**Comment by alikhan0498** [comment]
1.7.0. I'll update and see if the issue still presists. 

ETA :10 minutes

**Comment by alikhan0498** [comment]
I updated the mod and the issue if fixed.
