### ISSUE TITLE
Requesting 1.11.2 version bump

### ISSUE THREAD

**Issue by Squaredude** [Vanhal/ProgressiveAutomation#323]
Or, at least, point me in the direction to build a version bump for myself. Thanks.

**Comment by Vanhal** [comment]
Doesn't exist yet. A whole lot of changes need to be made to make it work with 1.11, it's in progress, but slow progress.

**Comment by Squaredude** [comment]
Have you taken a look at the CompatLayer library mod? Link: https://minecraft.curseforge.com/projects/compatlayer

**Comment by Psycho-Ray** [comment]
Done :]

**Comment by Squaredude** [comment]
That's awesome! Thanks a lot! :D

**Comment by Vanhal** [comment]
https://minecraft.curseforge.com/projects/progressive-automation-early-miner/files
