### ISSUE TITLE
Thermal foundation fluids, issuse with crafter

### ISSUE THREAD

**Issue by AidenHorsfield** [Vanhal/ProgressiveAutomation#324]
Obviously this is two mods working together and you may not have added compatability but when useing the crafting to craft the metals that need a fluid in thermal foundation (Signalum, lumium, enderium) you can interchange any fluid and it will still make them. For instance you can craft signalum with tree oil.

I understand this may not be a mod you added compatability for so its not a massive issuse just wanted to make you aware of it incase you did decide to add compatability

**Comment by Vanhal** [comment]
Well that just seems super weird....
