### ISSUE TITLE
Request: Planter right click upgrade

### ISSUE THREAD

**Issue by duncanwebb** [Vanhal/ProgressiveAutomation#325]
Would love to have an upgrade for the planter that right clicks crops to harvest them, would play well with mods like Pam's Harvestcraft and allow lots of different crop types in a small space.

Any chance?

**Comment by SanAndreasP** [comment]
It's already a config option!? Is it set to true for you? (in progressiveautomation.cfg, the option is called "RightClickPlants")

**Comment by duncanwebb** [comment]
Default is true, thanks for the help. So it breaks and harvest vanilla crops and right click harvestcraft and immersive engineering crops.

I was testing it on the Better with Mods Hemp and it is not being harvested, so I picked the wrong crop. I should have realized as I cannot add the seeds.

**Comment by Vanhal** [comment]
It will always attempt to right click the plant before breaking it. It might just be that the Hemp isn't being registered as a crop.

**Comment by duncanwebb** [comment]
Thanks this helps a bit. The ore dict name for hemp is cropHemp but the seed in this release doesn't have an ore dict name. So it should right click the mature plant and put the seeds and hemp in the output?

May be the seeds have been fixed as there are new files in the better with mods. I have assumed that you're parsing the ore dict name for crop and seed.

Sorry this is bit off the original request, do you want a new issue?

**Comment by Vanhal** [comment]
I've added support for the better with mods hemp now in 1.7.4 up later today.
