### ISSUE TITLE
Mystical Agriculture support

### ISSUE THREAD

**Issue by SanAndreasP** [Vanhal/ProgressiveAutomation#326]
Progressive Automation: 1.7.3
Mystical Agriculture: 1.4.5
Forge: 12.18.3.2254
Minecraft: 1.10.2

Planters have the option of supporting right-clicking plants instead of breaking and planting the seeds again. This works well with most crops I have, except for Mystical Agriculture ones, even though they themselves support right-clicking the crop manually.
What I want to ask is: can you add support for Mystical Agriculture crops?

Thanks in advance

**Comment by Vanhal** [comment]
Yeap will do.

**Comment by Vanhal** [comment]
Hmmmmm... So does Mystical Agriculture actually support right clicking on it's own, I am testing it now to see if it works and I can't even manually right click it.

Otherwise the crops works perfectly, harvested and replanted.

**Comment by SanAndreasP** [comment]
hm, right-clicking them works for me... it might be another mod doing it, though, so... I'll try to find out which one (later, as I'm not currently on my home PC).

The reason I want the right-clicking behavior is that I have a farm in a "row"-design and the way the planter currently does things with the mystical agriculture crops is messing up the design (so I've used EnderIOs farming stations for those, planters for everything else).

**Comment by Vanhal** [comment]
Is it a mod pack you're using? Which one and I can take a look.

**Comment by SanAndreasP** [comment]
no, it's a custom modpack. The only mods I can think of right now adding custom behavior are Pam's harvestcraft and Harvest Festival.

**Comment by SanAndreasP** [comment]
So after skimming through all mod configs, I can say that Pam's Harvestcraft does indeed allow most crops (including modded ones) to be manually harvested via right-click (it has a config option called "enableEasyHarvest")

**Comment by tia79** [comment]
Its probably Actually Additions. Those crops can be right clicked to harvest
