### ISSUE TITLE
[Bug] Animal Farmer not milking vanilla cows

### ISSUE THREAD

**Issue by omega025** [Vanhal/ProgressiveAutomation#327]
In Progressive Automation 1.7.3, the Animal Farmer seems to be stuck in "waiting" mode when tasked with milking vanilla cows and won't output milk buckets, despite having cows in range and having enough power and buckets.  When I revert to PA 1.7.0 (the last version I had downloaded before updating to 1.7.3), the Animal Farmer works fine.

**Comment by Vanhal** [comment]
You know I had been thinking that I might have broken this since I did the update.
I'll see about fixing it asap.

**Comment by Vanhal** [comment]
Will be fixed in 1.7.4 later today.
