### ISSUE TITLE
Pam's HarvestCraft not been harvested

### ISSUE THREAD

**Issue by duncanwebb** [Vanhal/ProgressiveAutomation#328]
I'm probably doing this incorrectly.

I placed a planter underneath nine different HarvestCraft crops, a hoe and some tiny charcoal. What is happening is that the crops are being replaced with a single crop and nothing in the harvester.

I'm just wondering what is happening to the food and why the crops are being replaced.

Versions Minecraft 1.10.2 and PA 1.7.4

![2017-04-05_18 55 45](https://cloud.githubusercontent.com/assets/4198031/24717137/b723085c-1a31-11e7-929b-acdd0455c149.png)

**Comment by ThugPug43** [comment]
My guess is it has something to do with Pam's seeds and crops being different items.
