### ISSUE TITLE
Question: Generators Slot

### ISSUE THREAD

**Issue by duncanwebb** [Vanhal/ProgressiveAutomation#332]
Hi,

What is the slot in the generators what is left of the fuel input used for, I haven't been able to find any information about it?

![image](https://cloud.githubusercontent.com/assets/4198031/26274269/4c82b35c-3d46-11e7-828e-a372ebedf938.png)

Thanks

**Comment by ktole1999** [comment]
you should be able to set in config if generators use power or fuel. slot would be used for temp power if enabled.

**Comment by duncanwebb** [comment]
It is for an RF Engine or in creative mode the Creative RF Engine, when enabled in the configuration, I tried a capacitor but that didn't work.

Many thanks
