### ISSUE TITLE
Request by FoolCraft DevTeam - Stop Planter When Output is Full

### ISSUE THREAD

**Issue by Jo-Mamma75** [Vanhal/ProgressiveAutomation#335]
Once again I would like to make another request of you.  Would it be possible to configure the various versions of the Planters to automatically stop harvesting crops if their internal inventory gets full?  This would help tremendously on multiplayer servers when players don't setup adequate overflow protection on their storage systems for the incoming crop yield.

We have some additional ideas/suggestions as well and would like to extend an invitation to our FoolCraft Dev Discord if you would like to collaborate with us.  If you are interested, please send us a private message on Curse and we'll provide the link.

Thank you for your consideration on this issue and we look forward to hearing from you at your earliest convenience.

**Comment by MikeSingularity** [comment]
This is currently possible via a config setting in progressiveautomation.cfg - you likely want pauseOnFullInventory, but you could disable allowInventoryOverflow if you wanted to be punitive.

pauseOnFullInventory (default: false) If true, it will stop the Chopper, Farmer,
Killer, Miner or Planter when it has no vacant inventory slots.

allowInventoryOverflow (default: true) If true, it performs the current default
behavior of dropping items into the world when the local inventory is
full. Changing this setting to false will simply delete the overflow
items while allowing the machine to keep running.

Hope this helps,

-Mike

**Comment by Jo-Mamma75** [comment]
Yeah, I feel like a complete moron now for not even noticing that in the config file.  Thanks @MikeSingularity
