### ISSUE TITLE
1.12 when?

### ISSUE THREAD

**Issue by syilphia** [Vanhal/ProgressiveAutomation#336]
the title is just a joke, i just want to ask if you have considered to update to 1.12 or just want to focus on 1.11.2 before later moving to 1.12, i love your mod (and how it has almost infinite potential) and want to use it when 1.12 stable, in fact one of the reason i still stay on 1.10.2 is your mod, so i just want to know

**Comment by 7934345** [comment]
The owner seems AKF for a little long time.

**Comment by Vanhal** [comment]
Once I've finished my current project I'll put aside some time to update to 1.11 and then onto 1.12

**Comment by syilphia** [comment]
thank you for the answer i'll wait patiently while playing invasion

**Comment by 7934345** [comment]
any plan for now?
@Vanhal

**Comment by TechnologicApe** [comment]
Any Updates?

**Comment by 7934345** [comment]
well well well, and where a u now?
@Vanhal

**Comment by bonnedav** [comment]
maby someone should make a fork to update? I am not a modder so i don't know how.

**Comment by Psycho-Ray** [comment]
I ended up losing my hard drive, and with it my forge workspace where everything worked. I'm playing minecraft again, and damn I want PA to work on 1.12, but I can't stop being lazy when it comes to my limited free time... I don't know, I might do it if I find a good list of things I should change to make PA work on 1.12 like I had found when I ported it to 1.11... But, honestly, I can't find enough motivation to do that just now.

**Comment by JaguarM** [comment]
PA is the only mod that can use custom tools with the auto miner. I really need that for a upcomming modpack.
