### ISSUE TITLE
When provided with a source of power, the capacitor does not draw power on any side.

### ISSUE THREAD

**Issue by SlyCedix** [Vanhal/ProgressiveAutomation#338]
http://i.imgur.com/xbDAuR3.png

As can be seen in the picture above, there is a generator, which is fully powered, and a diamond capacitor, connected with a Immersive Engineering wire, for visibility's sake.

The Capacitor, despite having power on the network, does not get filled with any RF.

This was tested with the machines directly next to each other, with an infinite RF source directly next to and connected with many different types of cables, with Ender IO energy conduits and Solar Flux Reborn Cables.

I did get the Capacitor to fill  up a few times while testing, and it seems the only way it does so is if the capacitor is looped back into itself, connecting a normal side and an input side, and if there is another block on the network accepting RF on the same line as the capacitor.

It seems that the capacitor is not requesting energy properly and can only siphon energy off of what is being requested by other machines.

**Comment by Waskom45** [comment]
I've been having a similar issue. I have a cable from my gen to the red dot on the capacitor. It wont charge the capacitor. I've found that if i break the cable connected to the capacitor and replace it, the capacitor will start to charge. But only once. i have to do this every time i want it to charge.
