### ISSUE TITLE
Chopper does not work with Meneril Logs from Integrated Dynamics

### ISSUE THREAD

**Issue by nroe1337** [Vanhal/ProgressiveAutomation#341]
I was hoping to automate gathering of meneril logs but the chopper does not seem to recognize the grown tree, but it does recognize the saplings and place them properly. The footprint of meneril trees is weird, its a + shape, but i had upgrades in the chopper to make it 7x7 (49) so im not sure what the issue is. The meneril logs are oredictionary'd as logs so im not sure the issue.

**Comment by Psycho-Ray** [comment]
I'll take a look at it and see what I can do.

**Comment by KocLobster** [comment]
So much for that fix
