### ISSUE TITLE
1.11.2 port request

### ISSUE THREAD

**Issue by orionSquared** [Vanhal/ProgressiveAutomation#342]
Good evening,

I think your mod would work fantastically in my modpack, but my pack is  a 1.11.2 pack. Is there a chance you're working on a port?

Thanks!

**Comment by Psycho-Ray** [comment]
Done :]

**Comment by orionSquared** [comment]
You're literally the best! Thanks! Can't wait for it to be released :3

**Comment by Psycho-Ray** [comment]
I just wanted the same as you do, bro xD
