### ISSUE TITLE
Item names in 1.11.2

### ISSUE THREAD

**Issue by orionSquared** [Vanhal/ProgressiveAutomation#346]
Good afternoon,

The names of all the items in the mod seem to be not formatted in JEI. Instead of just showing what it is, it says "item.crafter_diamond.name"

Small issue, not game breaking. Just thought I'd let you know :)

**Comment by Psycho-Ray** [comment]
I had it fixed. Strange. I remember there was a file conflict when Vanhal accepted my pull request, so I guess he deleted the wrong ones. Or maybe I've sent the wrong ones. Anyway, I'll upload the new ones.

**Comment by orionSquared** [comment]
Anytime. Happy to help. :)

**Comment by Vanhal** [comment]
Should be fixed in 1.7.6
