### ISSUE TITLE
Zero RF when RF support is turned off. 1.11.2

### ISSUE THREAD

**Issue by orionSquared** [Vanhal/ProgressiveAutomation#347]
Good afternoon,

When I turn off the RF support in the configs for this mod, an RF bar showing 0 RF still shows up in The One Probe. Not a major deal, not even game breaking. Just thought I'd point it out. :)

**Comment by Psycho-Ray** [comment]
Could you give me some more information? I'm not that intimate to PA's code, but I might be able to fix it.

**Comment by orionSquared** [comment]
Umm...what sort of information would you like? Sorry I'm not familiar with the modding side of things so I don't know what sort of stuff would be helpful to you.

**Comment by Psycho-Ray** [comment]
A screenshoot would be great. Also, what is The One Probe? And is it only a visual issue, or is it actually not working properly?

Off topic: Is the PA Wrench working for you? Just to make sure.

**Comment by orionSquared** [comment]
OOOOOH. The one probe is a McJty mod that's a successor to WAILA. To my knowledge, this is just a visual thing. I can screenshot in a bit. And I haven't tested the wrench yet but will when I grab the screenshot. I'm on a plane right now so it'll have to be after. Hope that's ok.

**Comment by Psycho-Ray** [comment]
So, do you have that screenshot?
