### ISSUE TITLE
missing language files

### ISSUE THREAD

**Issue by xxZSS** [Vanhal/ProgressiveAutomation#349]
Hello,

is there any way to involve the missing language files de_de and en_us into the 1.11.2 version?
Any doawnloaded file from any source is missing those files. :(

I allready tried to copy a language document from an older version into the actual version but it didnt work and all block names are shown as the default name (for example "tile.Miner.name").

Thanks alot in advance for any help or tips.

**Comment by Psycho-Ray** [comment]
There were a small confusion when Vanhal compiled the new version, and the old Language files ended up being selected over the newer ones. He seems to be quite busy these days, so I guess you should wait.

You could also pick up the custom jar I'll upload on my own PA fork and use that. It's identical to Vanhal's version, but the lang files are fixed. I hope he is ok with that...

**Comment by xxZSS** [comment]
pulling the files from your PA fork worked perfectly. Thanks alot for your help!

**Comment by Vanhal** [comment]
Fixed and uploaded to curse now, should be live in a bit.
