### ISSUE TITLE
Planter eating Agricraft crops

### ISSUE THREAD

**Issue by Master-Jynx** [Vanhal/ProgressiveAutomation#350]
I'm playing on a SMP sponge forge server using a modified FTB Beyond modpack
Minecraft 1.10.2
Forge 2477
Progresssive Automation 174
Agricraft a20

And several issues have come up.
1) because of Pam's Harvestcraft, crops can be planted directly (no seeds needed)
    But the planter won't let me plant crops in Agricraft Cropsticks unless they are seeds.
    I have to plant the sticks and crops before placing the the planter.
2)Planter will harvest agricraft crops (tested with 10/10/10 potatoes and 1/1/1/ carrots)
    but the items appear to be destroyed, nothing is being placed into the planters inventory.

wood and stone planters were tested.
hoes and power is being feed to it with EIO conduits.
they were tested with an rf engine and 8 range upgrades.

Edit: no.1 appears to be an Agricraft issue only.
        no.2 occurs in SSP,also.. 
Your fakeplayer, [VANHAL], will right click the correct cropstick
and reset its growth state, but nothing is ever dropped.

**Comment by Psycho-Ray** [comment]
I've recently made a fix to Pam's Harvestcraft that may fix at least a part of this problem.  However, it also changes a little bit of how the planter works, so I'll have to see what Vanhal thinks about it.

There are also a few things I want to fix before releasing such version. Anyway, thanks for reporting it o/
