### ISSUE TITLE
Planter + Enderlilys crash the Game

### ISSUE THREAD

**Issue by Holzstock** [Vanhal/ProgressiveAutomation#351]
When the Planter tries to harvest Enderlilys (from Extrautils2) the game crashes, also tried this with different versions of both mods, always the same result.

Some crash reports:

[crash-2017-10-15_21.29.16-server.txt](https://github.com/Vanhal/ProgressiveAutomation/files/1385757/crash-2017-10-15_21.29.16-server.txt)

[crash-2017-10-15_21.36.26-server.txt](https://github.com/Vanhal/ProgressiveAutomation/files/1385758/crash-2017-10-15_21.36.26-server.txt)

**Comment by Psycho-Ray** [comment]
I'm not sure if it's on PA side, but I'll see to it. Could you please describe me how Enderlilys are suposed to work? Is it any different than any Vanilla crop? How would you do to manually harvest it?

**Comment by Holzstock** [comment]
I think the only differences to vanilla crops are, that they are planted on grass or end-stone (not on farmland). Besides from that, there are no differences, exept that they need a really long time to grow (i think a bit more than 1 hour). I tried to deactivate the rightclick-mode in the config when growing them on normal grass the Planter tries to plant them on farmland (which causes them to drop as an item). Planting them on endstone seems to work.
