### ISSUE TITLE
Can't open auto crafter!

### ISSUE THREAD

**Issue by BOTKotel** [Vanhal/ProgressiveAutomation#363]
I am placing auto crafter. Try open it with right click and nothing happened. Crafter menu just don't pop up. Playing on 1.12.2 without other mods. Plis fix!

**Comment by zymex22** [comment]
same =)
cant open on both wooden, stone, iron crafter

**Comment by drutech** [comment]
Love the mod but add diamond crafter to this list.

**Comment by Vanhal** [comment]
It's all the same block so expected that if one doesn't work they all won't. I''ll have a look either tonight or wednesday
