### ISSUE TITLE
[1.12.2] Add a config option to enable upgrades to be dropped when a machine is mined

### ISSUE THREAD

**Issue by vizthex123** [Vanhal/ProgressiveAutomation#386]
Title. I'd like people to retain their upgrades in my modpack (as you can only put it about a dozen) instead of re-crafting them each time.

**Comment by Vanhal** [comment]
If you use the wrench on it you can pick it up with upgrades in it

**Comment by vizthex123** [comment]
Really? Cool. Guess that works then, thanks.
