### ISSUE TITLE
[Bug] Planter does not harvest nether wart

### ISSUE THREAD

**Issue by tjsd** [Vanhal/ProgressiveAutomation#43]
ProgressiveAutomation-1.7.10-1.4.12
Minecraft 1.7.10
Forge 1208
Biome: River

Progressive automation stone planter, it plants netherwart on soulsand, but it does not harvest while the wart is mature.

**Comment by ShadwDrgn** [comment]
Planter still doesn't harvest nether wart as of 1.10 version 1.6.53. 
![2016-12-21_15 05 09](https://cloud.githubusercontent.com/assets/2470781/21404405/1200561c-c78f-11e6-8e80-fd44aec03bb3.png)
