### ISSUE TITLE
Machine upgrades rework

### ISSUE THREAD

**Issue by Torins** [Vanhal/ProgressiveAutomation#71]
So yeah, the plan for this one would be to make it easier to create and use new upgrades in machines.
Currently we have two types of upgrades:
* level specific (wooden, stone, iron, diamond range upgrade)
* non level specific (filler, cobble gen, wither)
Additionally machines accept either an unlimited (range upgrade) amount or a single upgrade (everything else).

Goals:
* Easy configuration of which upgrades are used in which machine.
* Limit amount of lines [b]edited[/b] each time a new upgrade is added 

I expect that upgrades will continue to be level specific or not, with the former type being perhaps expanded beyond just range upgrades.
Machines will accept a limited (integer) or unlimited amount of a configured upgrade.

Code:
* int UpgradeableTileEntity.getUpgradeAmount(UpgradeType) - result will be a non negative number saying how many upgrades of a given type the entity has,
* boolean UpgradeableTileEntity.isUpgradeInstalled(UpgradeType) - result will be true if the upgrade is installed
* Some way of binding together level specific upgrades of a single type - probably the UpgradeType class (or enum?)

Things to consider:
* Marking which upgrades are available - how? Annotations? An overloaded method? a setUpgrades to be called in constructor? Depends on you want to achieve.
Will you want to limit upgrade B until upgrade A is installed? Then setXXX or addXXX is in order.
* Will the upgrade amount be configured at upgrade or machine level? (i.e. will planters accept a max of 3 upgrade X while choppers accept up to 10? Or will it be always like this - a machine can have up to 5 upgrades of type X)

**Comment by Vanhal** [comment]
This is closed now right....

**Comment by Torins** [comment]
Yeah, finally.. 
Again, sorry to take so long

**Comment by Vanhal** [comment]
No worries. I haven't been able to do much myself.
