### ISSUE TITLE
Progressive Automation EMC issue

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [Vanhal/ProgressiveAutomation#74]
Currently with Progressive automation installed alongside ProjectE, Wood and stone tools have insane EMC values due to seeing a crafting recipe for special wood swords from progressive automation, using Nether stars:

http://i.imgur.com/PTVlyHv.png
http://i.imgur.com/fz3Lit0.png
http://i.imgur.com/WnVGeDN.png

Not sure who's side this falls on, so I'l post on both Githubs.

Using Mod versions:
PROGRESSIVEAUTOMATION-1.7.10-1.5.6
PROJECTE-ALPHA 0.2D-DEV11

**Comment by IAA-ShRaPNeL** [comment]
Fixed on ProjectE's side.

**Comment by Vanhal** [comment]
Yeah I was gonna stay nothing to do with me :D

**Comment by IAA-ShRaPNeL** [comment]
Well, the Witherwood/stone tools are appearing as the default recipe, so there is that.

**Comment by Vanhal** [comment]
True, I'm going to be replacing the wither tools with actual tools soon anyway
