### ISSUE TITLE
Magical Crops Beta Bug

### ISSUE THREAD

**Issue by kurokuno** [Vanhal/ProgressiveAutomation#75]
it does not use a hoe however still plant on normal dirt un tilled when using planter and does not use any hoe durability however still plants harvests and so on not sure but i am guessing bug ?

**Comment by Vanhal** [comment]
Hoe will only use durability if it actually hoes the ground. The planter will try an plant the seed on dirt/grass before trying to hoe the ground. So technically the bug is with Magical Crops for not implementing canPlaceBlock and not PA, but I may implement a work around anyway.
