### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Gideonseymour** [Vanhal/ProgressiveAutomation#78]
---- Minecraft Crash Report ----
// Why is it breaking :(
 
Time: 1/11/15 2:05 AM
Description: Ticking block entity
 
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149694_d(Lnet/minecraft/world/World;III)Lnet/minecraft/item/Item;
        at net.minecraft.block.Block.getPickBlock(Block.java:1801)
        at com.dynious.refinedrelocation.helper.BlockHelper.getBlockDisplayName(BlockHelper.java:69)
        at com.dynious.refinedrelocation.helper.BlockHelper.getTileEntityDisplayName(BlockHelper.java:102)
        at com.dynious.refinedrelocation.tileentity.TileRelocator.func_70299_a(TileRelocator.java:983)
        at com.dynious.refinedrelocation.mods.part.PartRelocator.func_70299_a(PartRelocator.java:378)
        at codechicken.multipart.scalatraits.TIInventoryTile$class.setInventorySlotContents(TIInventoryTile.scala:78)
        at codechicken.multipart.scalatraits.JInventoryTile$class.func_70299_a(TIInventoryTile.scala:131)
        at TileMultipart_cmp$$22.func_70299_a(Unknown Source)
        at com.vanhal.progressiveautomation.entities.BaseTileEntity.addtoExtInventory(BaseTileEntity.java:540)
        at com.vanhal.progressiveautomation.entities.BaseTileEntity.checkInventory(BaseTileEntity.java:498)
        at com.vanhal.progressiveautomation.entities.miner.TileMiner.func_145845_h(TileMiner.java:71)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Stacktrace:
        at net.minecraft.block.Block.getPickBlock(Block.java:1801)
        at com.dynious.refinedrelocation.helper.BlockHelper.getBlockDisplayName(BlockHelper.java:69)
        at com.dynious.refinedrelocation.helper.BlockHelper.getTileEntityDisplayName(BlockHelper.java:102)
        at com.dynious.refinedrelocation.tileentity.TileRelocator.func_70299_a(TileRelocator.java:983)
        at com.dynious.refinedrelocation.mods.part.PartRelocator.func_70299_a(PartRelocator.java:378)
        at codechicken.multipart.scalatraits.TIInventoryTile$class.setInventorySlotContents(TIInventoryTile.scala:78)
        at codechicken.multipart.scalatraits.JInventoryTile$class.func_70299_a(TIInventoryTile.scala:131)
        at TileMultipart_cmp$$22.func_70299_a(Unknown Source)
        at com.vanhal.progressiveautomation.entities.BaseTileEntity.addtoExtInventory(BaseTileEntity.java:540)
        at com.vanhal.progressiveautomation.entities.BaseTileEntity.checkInventory(BaseTileEntity.java:498)
        at com.vanhal.progressiveautomation.entities.miner.TileMiner.func_145845_h(TileMiner.java:71)
 
-- Block entity being ticked --
Details:
        Name: TileMinerStone // com.vanhal.progressiveautomation.entities.miner.TileMinerStone
        Block type: ID #1306 (tile.MinerStone // com.vanhal.progressiveautomation.blocks.BlockMiner)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (1734,71,-602), Chunk: (at 6,4,6 in 108,-38; contains blocks 1728,0,-608 to 1743,255,-593), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,0,-1024 to 2047,255,-513)
        Actual block type: ID #1306 (tile.MinerStone // com.vanhal.progressiveautomation.blocks.BlockMiner)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
 
-- Affected level --
Details:
        Level name: world
        All players: 3 total; [EntityPlayerMP['Gideonseymour'/67880359, l='world', x=886.60, y=69.63, z=-828.69], EntityPlayerMP['goreae'/67995750, l='world', x=2160.70, y=63.00, z=-729.30], EntityPlayerMP['russell4'/69687926, l='world', x=1734.59, y=70.88, z=-599.95]]
        Chunk stats: ServerChunkCache: 1811 Drop: 0
        Level seed: -2037064873035042864
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options:
        Level spawn location: World: (1000,71,-429), Chunk: (at 8,4,3 in 62,-27; contains blocks 992,0,-432 to 1007,255,-417), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
        Level time: 5665850 game time, 7272716 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 17324 (now: true), thunder time: 11223 (now: true)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
 
-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.12-0.bpo.1-amd64
        Java Version: 1.7.0, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 678635088 bytes (647 MB) / 2370568192 bytes (2260 MB) up to 18407424000 bytes (17554 MB)
        JVM Flags: 21 total; -Xms2048M -XX:PermSize=384m -XX:MaxPermSize=768m -XX:-UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseLargePages -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ParallelGCThreads=1
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 34
        FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 90 mods loaded, 89 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML{7.10.85.1277} [Forge Mod Loader] (forge-1.7.10-10.13.2.1277-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forge{10.13.2.1277} [Minecraft Forge] (forge-1.7.10-10.13.2.1277-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        appliedenergistics2-core{rv2-beta-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FEPreLoader{1.4.0-beta4} [Forge Essentials|PreLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AgriCraft{1.7.10-1.1.0a} [AgriCraft] (AgriCraft-1.1.0a (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AppleCore{1.0.1} [AppleCore] (AppleCore-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        appliedenergistics2{rv2-beta-1} [Applied Energistics 2] (appliedenergistics2-rv2-beta-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        asielib{0.3.4} [asielib] (AsieLib-1.7.10-0.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BigReactors{0.4.0A} [Big Reactors] (BigReactors-0.4.0A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AWWayofTime{v1.3.0} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        bluepower{0.1.766} [Blue Power] (BluePower-1.7.10-0.1.766-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Botania{r1.3-149} [Botania] (Botania r1.3-149.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CarpentersBlocks{3.3.3} [Carpenter's Blocks] (Carpenter's Blocks v3.3.3 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        climatecontrol{0.4} [Climate Control] (ClimateControl-0.4.beta17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CustomOreGen{1.2.17} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ImmibisCore{59.0.1} [Immibis Core] (immibis-core-59.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        DimensionalAnchors{59.0.2} [Dimensional Anchors] (dimensional-anchor-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        eirairc{mc1.7.10-v1.7.29} [EiraIRC] (eirairc-mc1.7.10-v1.7.52 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        EnderIO{1.7.10-2.2.5.311} [Ender IO] (EnderIO-1.7.10-2.2.5.311.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        EnderStorage{1.4.5.null} [EnderStorage] (EnderStorage-1.7.10-1.4.5.X.3-MR208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        EnderTech{1.7.10-0.3.0.358} [EnderTech] (EnderTech-1.7.10-0.3.0.358.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        enderutilities{0.3.5.1} [Ender Utilities] (enderutilities-1.7.10-0.3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FastCraft{1.12} [FastCraft] (fastcraft-1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        flora{1.0} [Fluids and Liquids on Ridiculous Armor] (FLORA-1.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ForgeEssentials{1.4.0-beta4} [Forge Essentials] (forgeessentials-1.7.10-1.4.0-beta4-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        liquidDirt{1.0} [Liquid Dirt] (liquidDirt-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ModularArmour{0.1.4} [Modular Armour] (ModularArmour-1.7.10-0.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-436.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OresPlus{0.7.3.41B} [OresPlus] (OresPlus-0.7.3.41B.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10e.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Ping{%MOD_VERSION} [Ping] (Ping-1.7.X-1.0.2.B6-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        progressiveautomation{1.5.6} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.5.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjectE{1.7.10-0.2d-dev13} [ProjectE] (ProjectE-1.7.10-0.2d-dev13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RandomThings{2.2.2} [Random Things] (RandomThings-2.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RefinedRelocation{1.0.6h} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.6h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        rftools{2.01} [RFTools] (rftools-2.01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ttCore{MC1.7.10-0.1.0-53} [ttCore] (ttCore-MC1.7.10-0.1.0-53.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        SimpleAchievements{MC1.7.10-1.1.0-15} [Simple Achievements] (SimpleAchievements-MC1.7.10-1.1.0-15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        StevesFactoryManager{A92} [Steve's Factory Manager] (StevesFactoryManagerA92.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        erebus{0.2pre11c} [Erebus] (TheErebus-0.2pre11c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ToolUtilities{0.0.1} [Tool Utilities] (ToolUtilities-MC1.7.10-0.0.1-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TML{4.0.0} [TooMuchLoot] (TooMuchLoot-1.7.10-4.0.0.B25.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TooMuchRain{%VERSION%} [TooMuchRain] (TooMuchRain-1.7.2-1.0.0-b5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        witchery{0.20.6} [Witchery] (witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        worldedit{6.0.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        YALSM{2.1.3} [Yet Another Leather Smelting Mod] (yalsm-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        yampst{1.3.3} [YAMPST] (Yampst-Phoenix Reborn-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        denseores{1.0} [Dense Ores] (denseores-1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        HungerOverhaul{1.7.10-beta.4.jenkins44} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        asielibcore{} [AsieLib CoreMod] (minecraft.jar) Unloaded->Disabled
        AE2 Version: beta rv2-beta-1 for Forge 10.13.2.1230
        ForgeEssentials: Build information: Build number is: 364, Build hash is: 82eedf3, Modules loaded: Afterlife, AuthLogin, Chat, Commands, Economy, Multiworld, Permissions, Protection, Remote, Scripting, ServerVote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder
        AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 5 / 33; [EntityPlayerMP['Gideonseymour'/67880359, l='world', x=886.60, y=69.63, z=-828.69], EntityPlayerMP['goreae'/67995750, l='world', x=2160.70, y=63.00, z=-729.30], EntityPlayerMP['Shunraiki'/68055773, l='world', x=89.34, y=4.00, z=-226.41], EntityPlayerMP['numbah90'/68638215, l='world', x=75.98, y=41.00, z=3.07], EntityPlayerMP['russell4'/69687926, l='world', x=1734.59, y=70.88, z=-599.95]]
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

**Comment by Gideonseymour** [comment]
I'm not certain if this is a Refined Relocation or Progressive Automation crash, so I'm reporting it in both places.

**Comment by Vanhal** [comment]
Is it possible that a miner has a refined relocation chest/container on top of it?
Or, is someone middle clicking something when it happens.....

**Comment by Gideonseymour** [comment]
It's a Refined Relocation crash - they're trying to reference something server-side. Sorry to bother you!

**Comment by Dynious** [comment]
The crash part is my issue (getting the name of a block on server side), but the crash is a line to warn the user that a mod is inserting into Relocators wrongly! I'm posting this to warn you, because this could also cause issues with other mods.

When inserting into an IInventory you should check if it's an ISidedInventory and check for the insertion  conditions. You should try to output to only the slots accessible from the side you are outputting to, and (this is the thing that's causing the warning) call ISidedInventory#canInsertItem!
