### ISSUE TITLE
Support ISidedInventory and perhaps various pipes when pushing items out of machines

### ISSUE THREAD

**Issue by Torins** [Vanhal/ProgressiveAutomation#81]
Inspired by #78.

**Comment by Dynious** [comment]
If you want you can copy what I use for pushing into pipes/inventories. Will also put pushed items onto stacks of the same item first before creating a new stack in the inventory (like hoppers and most mods). Supports TE, BC & RR pipes.

https://github.com/Dynious/RefinedRelocation/blob/master/src/main/java/com/dynious/refinedrelocation/helper/IOHelper.java#L141

**Comment by Vanhal** [comment]
Kinda done.....
