### ISSUE TITLE
Upgrade idea

### ISSUE THREAD

**Issue by Torins** [Vanhal/ProgressiveAutomation#82]
How about an overclock upgrade?

Increases speed (or lowers cooldown, or both?) by a %, but either has a % chance to use more durability on the tool or uses more energy?

**Comment by Vanhal** [comment]
But higher tier machines go faster already....

**Comment by Torins** [comment]
Yeah, but they go faster without any downside. 
The proposed upgrade would increase speed at the cost of increased resources per operation (faster tool wear out, or more energy usage).
It was just a random idea anyhow, if you don't like it, just close the issue :)

**Comment by Vanhal** [comment]
ah i see. Yeah that's not a bad idea. It would definitely be at a cost of durability rather than fuel/power
