### ISSUE TITLE
Pushing to external inventory not checking the correct ISided calls!

### ISSUE THREAD

**Issue by Vanhal** [Vanhal/ProgressiveAutomation#83]
The crash part is my issue (getting the name of a block on server side), but the crash is a line to warn the user that a mod is inserting into Relocators wrongly! I'm posting this to warn you, because this could also cause issues with other mods.

When inserting into an IInventory you should check if it's an ISidedInventory and check for the insertion  conditions. You should try to output to only the slots accessible from the side you are outputting to, and (this is the thing that's causing the warning) call ISidedInventory#canInsertItem!

Link to code:
https://github.com/Vanhal/ProgressiveAutomation/blob/master/src/main/java/com/vanhal/progressiveautomation/entities/BaseTileEntity.java#L521

**Comment by Torins** [comment]
Duplicated by #81

**Comment by Vanhal** [comment]
Yeah kinda, The other is to actually support it, this is more just fixing the bug that is already there.

**Comment by Torins** [comment]
Ah, my bad then. 
Anyhow, what do you think of taking on Dynious' offer and using the code from his IOHelper class? That way it'll both fix the issue at hand and add pipe/duct compatibility?

**Comment by Vanhal** [comment]
Yeah might be an idea, I haven't read his code yet however. I'm just gonna patch this quickly now to avoid any bugs down the line.
