### ISSUE TITLE
Planter Broken

### ISSUE THREAD

**Issue by lanman14444** [Vanhal/ProgressiveAutomation#86]
Mod Version 1.5.16
Forge Versions 10.13.1230 + 10.13.1291 + 10.13.1277

Steps to reproduce:
Place a planter or any tier, and give it the necessary tiered items items. And it does nothing, and the interface just says Waiting.

I have tried tilling the land around it, using a damage hoe, and running PA with no other mods. 

Also, when Waila is installed this spams the server/client logs with
http://pastebin.com/01WfytRr

**Comment by Vanhal** [comment]
Is the planter underneath the dirt?
The second bit I'll fix

**Comment by Vanhal** [comment]
I can't actually seem to replicate the log spam. What version of waila do you have? Any Waila add-on installed as well?

**Comment by lanman14444** [comment]
I had the planter in the wrong place, and the spam seems on and off I tried re-producing it and it didn't appear instantly it took 1 minute or two. The waila versions are  Waila 1.5.7a (because and ChickenBones hasn't made a 1.0.4.x recommended yet) Waila Harvestability 1.1.1.
