### ISSUE TITLE
Diamond Miner and chopper not increasing range with diamond upgrade 1.5.16

### ISSUE THREAD

**Issue by arkD** [Vanhal/ProgressiveAutomation#88]
im using forge 1291, progressive automation 1.5.16
i survival made and creative spawned both the diamond miner and chopper, when i place diamond upgrade in the machines the range does not increase, i tried the other upgrades and they seem to function fine as well as the lower tiers. i check the config but couldnt find anything that would disable this effect. 

i would be happy to provide screen shots or any other information you require.
also love the mod, great work!

**Comment by Vanhal** [comment]
Fixed, new version pushed out, 1.5.17: https://drone.io/github.com/Vanhal/ModJam/files
Will be up on curse later.

**Comment by arkD** [comment]
thanks for the quick fix!, ill be sure to update tomorrow. your awesome!

**Comment by Vanhal** [comment]
It was definitely game breaking, needed an update quickly!
