### ISSUE TITLE
Miners stop mining upon hitting stone, but carry on filling cobble.

### ISSUE THREAD

**Issue by whichonespink44** [Vanhal/ProgressiveAutomation#90]
I posted this in the MCF thread, but then realised I should've posted it here instead, so apologies for the double post.

Anyway, here's the issue I'm having...

The Miners (all variants) stop mining as soon as they hit the first instance of stone, but they continue to replace the blocks underneath them with cobble, even though the amount of cobble in the Miner doesn't decrease after it hits the first instance of stone.

So... with a full stack of cobble in the Miner, it goes like this... Miner mines 3 blocks of dirt, replacing them with cobble (61 cobble + 3 dirt in the Miner), and then it carries on replacing all blocks underneath it with cobble (but there's still 61 cobble + 3 dirt in the miner).

I'm running Forge 1.7.10-10.13.2.1291 with Progressive Automation 1.7.10-1.5.18, and no other mods installed.

Any help would be greatly appreciated. My kids and I really love the other machines, and it would be great to get the Miners working as well.

Thanks in advance.

**Comment by Vanhal** [comment]
Could it be that the stone is being mined, turns to cobble stone and gets put straight into the cobblestone slot? To test that you could put a silk touch pick into the miner and see what happens.

**Comment by whichonespink44** [comment]
That did the trick! I feel a bit silly now for not figuring that out myself, but thanks so much for the quick reply - much appreciated. :)

**Comment by Vanhal** [comment]
Hahah, No worries, the exact same thing happened to me the other day when I was playing :D
