### ISSUE TITLE
[Feature request] Redstone Flux Power

### ISSUE THREAD

**Issue by Maelstraz** [Vanhal/ProgressiveAutomation#92]
With EnderIO you can use Wireless Charger to recharge your RF-powered tools (Darksteel, Restone Arsenal, Tinkers' RF upgrade).

But would be cool, if RF-engine in machine can do the same (ofc only for this machine and this tool).
Exspecially, when you don't have EnderIO. xD

**Comment by Vanhal** [comment]
Do the tools charge while in an chest or similar? Depending on how the EnderIO wireless charger works it should actually charge the RF engine is it's in your inventory but I haven't actually used the wireless charger myself.

**Comment by Vanhal** [comment]
Yeap just tested it. THe wireless charger does in fact charge RF engines when in your inventory, but since it is only meant to charge things in a players inventory that's all it can do.
