### ISSUE TITLE
mining redstone crash and corrupt world

### ISSUE THREAD

**Issue by alicorna76** [Vanhal/ProgressiveAutomation#93]
I been trying to figure out which mod was making my game crash. i love your mod but can't mine redstone....here's the crash report
---- Minecraft Crash Report ----
// Sorry :(

Time: 2/23/15 12:28 AM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=power, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockState{block=minecraft:lit_redstone_ore, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:158)
	at codechicken.nei.DefaultHighlightHandler.handleTextData(DefaultHighlightHandler.java:32)
	at codechicken.nei.api.ItemInfo.getText(ItemInfo.java:498)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:52)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:348)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:158)
	at codechicken.nei.DefaultHighlightHandler.handleTextData(DefaultHighlightHandler.java:32)
	at codechicken.nei.api.ItemInfo.getText(ItemInfo.java:498)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:52)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['alicorna'/196, l='MpServer', x=161.79, y=13.00, z=20.89]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 212.00,64.00,176.00 - World: (212,64,176), Chunk: (at 4,4,0 in 13,11; contains blocks 208,0,176 to 223,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 122150 game time, 132227 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 47 total; [EntitySheep['Sheep'/1289234, l='MpServer', x=232.84, y=68.00, z=23.28], EntitySheep['Sheep'/1289233, l='MpServer', x=225.00, y=63.00, z=-35.94], EntitySheep['Sheep'/1381651, l='MpServer', x=94.03, y=75.00, z=-13.97], EntitySheep['Sheep'/1381650, l='MpServer', x=90.81, y=76.00, z=-2.84], EntitySheep['Sheep'/1381637, l='MpServer', x=90.31, y=76.00, z=20.53], EntityBat['Bat'/1381636, l='MpServer', x=85.25, y=35.10, z=22.25], EntityItem['item.item.egg'/1267457, l='MpServer', x=201.44, y=66.00, z=70.03], EntityBat['Bat'/1381635, l='MpServer', x=95.75, y=24.10, z=-17.50], EntitySheep['Sheep'/1381647, l='MpServer', x=82.53, y=75.00, z=33.31], EntitySheep['Sheep'/1381646, l='MpServer', x=82.19, y=74.00, z=34.69], EntityItem['item.item.egg'/1375922, l='MpServer', x=188.38, y=67.00, z=75.97], EntitySheep['Sheep'/46, l='MpServer', x=106.78, y=78.00, z=8.16], EntitySheep['Sheep'/47, l='MpServer', x=110.47, y=79.00, z=8.00], EntitySheep['Sheep'/49, l='MpServer', x=100.66, y=72.00, z=42.88], EntitySheep['Sheep'/52, l='MpServer', x=112.47, y=79.00, z=13.19], EntitySheep['Sheep'/54, l='MpServer', x=121.84, y=78.00, z=17.25], EntityItem['item.item.egg'/1338659, l='MpServer', x=181.66, y=62.00, z=73.13], EntitySheep['Sheep'/1359316, l='MpServer', x=217.53, y=64.00, z=-59.06], EntitySheep['Sheep'/1359317, l='MpServer', x=217.72, y=64.00, z=-55.84], EntitySheep['Sheep'/639176, l='MpServer', x=96.34, y=75.00, z=3.81], EntitySheep['Sheep'/1359318, l='MpServer', x=219.06, y=64.00, z=-56.97], EntitySheep['Sheep'/67, l='MpServer', x=135.66, y=71.00, z=18.50], EntitySheep['Sheep'/1359319, l='MpServer', x=211.69, y=64.00, z=-58.16], EntitySheep['Sheep'/68, l='MpServer', x=141.03, y=69.00, z=18.13], EntitySheep['Sheep'/69, l='MpServer', x=135.75, y=61.50, z=45.22], EntitySheep['Sheep'/1289300, l='MpServer', x=227.16, y=69.00, z=25.16], EntityChicken['Chicken'/79, l='MpServer', x=181.53, y=62.69, z=73.03], EntitySheep['Sheep'/81, l='MpServer', x=184.78, y=65.00, z=61.44], EntityChicken['Chicken'/82, l='MpServer', x=201.69, y=66.00, z=70.59], EntityChicken['Chicken'/84, l='MpServer', x=192.56, y=67.00, z=76.72], EntityChicken['Chicken'/85, l='MpServer', x=188.50, y=67.00, z=75.53], EntitySheep['Sheep'/86, l='MpServer', x=177.44, y=68.00, z=64.53], EntitySheep['Sheep'/969304, l='MpServer', x=221.13, y=63.00, z=-45.91], EntityChicken['Chicken'/87, l='MpServer', x=181.50, y=61.59, z=92.78], EntityPlayerSP['alicorna'/196, l='MpServer', x=161.79, y=13.00, z=20.89], EntitySheep['Sheep'/89, l='MpServer', x=197.41, y=66.00, z=80.31], EntitySheep['Sheep'/96, l='MpServer', x=195.31, y=67.00, z=51.50], EntitySheep['Sheep'/97, l='MpServer', x=193.91, y=62.00, z=84.94], EntitySheep['Sheep'/98, l='MpServer', x=203.03, y=64.00, z=97.13], EntityBat['Bat'/1331952, l='MpServer', x=183.44, y=15.82, z=13.40], EntitySheep['Sheep'/106, l='MpServer', x=222.91, y=70.00, z=36.91], EntitySheep['Sheep'/107, l='MpServer', x=209.72, y=63.00, z=54.84], EntityItem['item.item.egg'/1344635, l='MpServer', x=193.19, y=67.00, z=76.50], EntitySheep['Sheep'/663160, l='MpServer', x=124.53, y=76.00, z=-11.34], EntitySheep['Sheep'/1359329, l='MpServer', x=198.66, y=64.00, z=-48.47], EntitySheep['Sheep'/1359330, l='MpServer', x=196.06, y=65.00, z=-60.50], EntitySheep['Sheep'/663159, l='MpServer', x=99.50, y=75.00, z=-4.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:350)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2489)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 122379344 bytes (116 MB) / 473591808 bytes (451 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.26.1299 Minecraft Forge 11.14.0.1299 10 mods loaded, 10 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{8.0.26.1299} [Forge Mod Loader] (forge-1.8-11.14.0.1299.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{11.14.0.1299} [Minecraft Forge] (forge-1.8-11.14.0.1299.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.5.82} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.82-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.3.3} [Damage Indicators] ([1.8]DamageIndicatorsMod-3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wuppy29_harderpeaceful{1.8.0} [Harder Peaceful] (Harder Peaceful 1.8.0-1.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wuppy29_peacefulpack{1.1.9.0} [Peacefulpack] (Peacefulpack 1.8.0-1.1.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	progressiveautomation{1.5.23} [Progressive Automation] (ProgressiveAutomation-1.8-1.5.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	XaeroMinimap{1.2.4} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.8-Forge11.14.0.1299
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 3200 Graphics     GL version 2.1.8794, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
-------------------------------------------------------------------------------------------------------------------------------
i don't know how to read this nor if this is only happening to me.

**Comment by Vanhal** [comment]
Is this in 1.8 yeah? Are you running any other mods?

**Comment by Vanhal** [comment]
I just tried mining redstone there and it worked without any crashes. From the crash log it actually seems to be an issue with NEI.

**Comment by alicorna76** [comment]
Ok, thanks for checking it out
