### ISSUE TITLE
1.8 generators not working to power open computers systems

### ISSUE THREAD

**Issue by technolem** [Vanhal/ProgressiveAutomation#95]
As the title says, the power systems of each mod work amongst themselves, and open computers recognizes progressive automation as an RF mod. But OC's power converter won't take power from the diamond generator.

**Comment by Vanhal** [comment]
Ah, yeah, I suspected as much. It's because there is currently no official RF api, so I just ported my own version. Unless other people use my version or I switch to theirs they won't work between each other. I'll reach out to the opencomputer peep and see what they are using.

**Comment by technolem** [comment]
Well, I thought it was something like that. I only found these two mods using rf (or any power really) in 1.8. Open computers has a setting to disable power, I just thought I try this to see if it'd work.

**Comment by Vanhal** [comment]
fnueckehas readded the RF API to the newest builds. I tested it out and it seems to work fine!
![2015-03-09_08 36 25](https://cloud.githubusercontent.com/assets/7526890/6551919/a3cd3142-c637-11e4-8d52-81ae450b1b46.png)

Referenced here https://github.com/MightyPirates/OpenComputers/issues/953

**Comment by technolem** [comment]
Yep, working here too!
