### ISSUE TITLE
Miner skips "mining" with tinkers' construct tools

### ISSUE THREAD

**Issue by Nezraddin** [Vanhal/ProgressiveAutomation#98]
Hello *waves*

I'm actually not sure if that is considered a "bug", but it's a bit confusing:
When a pickaxe from tinkers' construct reaches 0 durability the miner doesn'T stop and tell you "Need pickaxe", it seems to just suddenly skip everything which would require the pickaxe (lowers the number of how many blocks to mine aswell) and after the shovel-part is done says "Finished".
A bit confusing that it doesn't stop and actually simply beging to ignore blocks. 

Not sure if the shovel would do the same, wasn't able to get it's durability to 0 while writing this.

I used a stone-pickaxe, made from wooden toolrod, obsidian tool binding, stone head and two reinforced upgrades (in case that is important, so it had reinforced V)

**Comment by Vanhal** [comment]
Oh, Originally it was meant to keep going, but using the broken pickaxe. Putting a new pickaxe in (or replacing the old one) should get it to mine everything it skipped though.

**Comment by Nezraddin** [comment]
Noticed about putting a new pickaxe in after a while :)
Guess it's not a bug then. Thanks for clearing this up (was really a bit confusing, since I first thought it was using the broken pickaxe to keep mining)

(Shall I close the issue again, or is that something that probably needs work on, so to let it open for now?)
